### ISSUE TITLE
Responder "Friends status" does not say anything when friend comes online

### ISSUE THREAD

**Issue by Taomyn** [EDCD/EDDI#1024]
## EDDI version in which issue found
3.3-rc1 (and earlier versions for a long time)

## Steps to reproduce
1. Enable "Friends status" in speech responder
2. Wait for friend to come on-line

## Expected
EDDI should speak that friend has come on-line

## Observed
EDDI does nothing

## Investigation
This has probably been happening to me for many months, I can't remember when it first stopped working, but it only happens when friends come on-line. I get EDDI speaking when they go off-line.

I use a custom personality but all I do to "Friends status" is enable it. Pressing test returns "I don't know who you are talking about".

An example from my journal tonight that did not trigger the voice was:
```
{
  "timestamp": "2018-12-19T20:39:01Z",
  "event": "Friends",
  "Status": "Online",
  "Name": "Milo Beaublanc"
}
```

**Comment by Tkael** [comment]
The events don't indicate whether they are being written as part of loading into the game or at a later time, so we have to strike a balance that doesn't flood you with status messages when you first load into the game and yet isn't silent.

The game floods us with `Friends status` events immediately after the game starts. We have to suppress those, and we do this by registering each friend when they first appear in the session's journal log rather than firing an event the first time that they appear. 

Since the journal can contain repeats of the same status for the same commander, we also suppresses repetition of the same status and only fire an event when a change in status occurs.

e.g. If this is the first time we're seeing this friend in this play session then we would fire an event on the second instance if the event below. If we've seen this friend before then we may fire an event for the first entry (**if** the friend's status has changed) but not for the second (since the friend's status is unchanged)
```json
{ "timestamp":"2018-11-10T02:48:06Z", "event":"Friends", "Status":"Online", "Name":"Hoodathunk" }
{ "timestamp":"2018-11-10T02:49:51Z", "event":"Friends", "Status":"Online", "Name":"Hoodathunk" }
```

I'm submitting a change that fixes testing for this script, but we do need to continue to apply some filtering to status messages for the reasons noted above.

**Comment by richardbuckle** [comment]
You already have that option. Go to the Speech Responder tab, make a copy of the default personality, if you haven't already, and check the box beside the Friends status row.

**Comment by Taomyn** [comment]
> You already have that option. Go to the Speech Responder tab, make a copy of the default personality, if you haven't already, and check the box beside the Friends status row.

That only enables the alert on friends going on/off-line, it doesn't disable the code that prevents the multiple alerts when starting the game etc I played for 4 hrs tonight, I saw maybe 10-15 in-game alerts of friends coming'n'going, but not once did EDDI tell me anything.
