### ISSUE TITLE
CurrentSystem main star is not set after `Jump` event

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#1052]
https://forums.frontier.co.uk/showthread.php/387955-EDDI-2-4-Bring-your-cockpit-to-life?p=7299213&viewfull=1#post7299213  

Reviewing EDDI.cs, we start from a new StarSystem and set the information available from the event. We should consider using `StarSystemSqlLiteRepository.GetOrCreateStarSystem ` rather than starting from an empty system.

**Comment by Tkael** [comment]
I may have been premature in my assessment on this. The StarSystem information is set during the `FSDEngaged` event, or by the `FSDJump` event if it isn't set when that event occurs.
This error may still occur if EDSM fails to return any bodies when we are getting data.

**Comment by Bigscouser** [comment]
Hi, don't know if this is directly related, but I get a voice message saying "Star information not correctly set, please jump out and jump back in to the system, or log out and log back in." This seems to happen every time I scan a Nav Beacon, rather than entering a system or running the Discovery/FSS scanner.

Given you're not in FSD/Supercruise for Nav Beacon scans, I wondered if it was related?

**Comment by Tkael** [comment]
Not directly related, but I'm working on that issue too.
