### ISSUE TITLE
What's going on with the EDDI installer ?

### ISSUE THREAD

**Issue by nepomuk16321** [EDCD/EDDI#1149]
## EDDI version in which issue found
The problem exists from v3.3

## Steps to reproduce
Since version 3.3 and following, I can't install EDDI anymore (reinstall). But with version 3.1.2 this is still possible.

## Expected
[describe what you expected to happen]

## Observed
[describe what happened instead]

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
Please be more descriptive? What do you mean when you say you can't install?
Are you downloading the installer from Github or the in-app upgrade button? In there some error when you run the installer? Does it just silently fail?

**Comment by nepomuk16321** [comment]
Until the last version (v 3.3.4-rc3) I always installed the latest version via the in-app-update-button. This worked. Now I wanted to go back to version v 3.3, because this version didn't cause me any problems (star scanned or star report). So I uninstalled EDDI (v 3.3.4-rc3) completely, pulled version 3.3 from github and wanted to install it. But after a double click on the exe file nothing happened !
The same happened with version 3.3.1 ! Only with version 3.1.2 I could install EDDI. The update via the in-app-update-button to version 3.3.4-rc3 worked again.
I had hoped to be able to use an older version, since there the problems of some scripts (star scanned, star report) did not occur, but unfortunately this does not work. I had also hoped that EDDI would now start faster as a VA-plug-in. The start time of EDDI as VA-plug-in has dragged on with the time up to one minute. 

Translated with www.DeepL.com/Translator

Thanks for your help and sorry for the incomplete error message.

nepomuk16321

**Comment by Tkael** [comment]
I'm not certain what the problem is, but if I download and install version 3.3 it installs and runs (though it only runs in "safe mode" with monitors and responders disabled to prevent sending obsolete data to other services or corrupting the database).
Version 3.3.3 also installs and runs correctly, with all responders and monitors working.

If you would like me to investigate further, please install version 3.3.3 and attempt to run it. Once you have done this, please attach a copy of the most recent log file (located at %APPDATA%\EDDI on your computer) to this issue so that I can see what errors are being recorded.

**Comment by nepomuk16321** [comment]
Ok, I have now installed EDDI v3.3.4-rc3 and this version is running. Maybe the downloaded version 3.3 of github was also faulty, at least after a double click nothing happened. I think the problem is solved and doesn't need to be followed up.
Thanks for your help !

Greetings nepomuk
