### ISSUE TITLE
Issue with 'Terraformable' Reporting

### ISSUE THREAD

**Issue by mearmortal** [EDCD/EDDI#1224]
## EDDI version in which issue found
3.3.6 with VA

## Steps to reproduce
Not sure I can reproduce what doesn't appear to happen.

## Expected
I would expect to here something about the object being terraformable, or the word 'terraformable' in the voice feedback.

## Observed
I'm pretty sure I've been lookng for it, as I'm scanning every terraformable world, but I'm having to search through the logs in EDDiscovery to identify them.

## Investigation
I wasn't so focused in earlier versions, so can't comment on them.
I did find this in the description:
terraformstate Whether the body can be, is in the process of, or has been terraformed (only available if DSS equipped)
Now that ED is on 3.3, the DSS is no longer a module, is this the reason it's not reporting it.

**Comment by Darkcyde13** [comment]
The default Body Report script needed a change a little while ago, if I remember correctly.  A change by Frontier (surprise, surprise) meant that the default doesn't work anymore, I was expecting this to have been fixed by now though.

Anyway, find this bit of code in the Body Report script:-
```
    {if reportTerraformState > 0:
        {if reportbody.terraformstate = "Terraformable":
            terraformable
        |elif reportbody.terraformstate = "Terraformed":
            terraformed
        }
    }
```

And replace it with this:-
```
    {if reportTerraformState = 1:
        {if reportbody.terraformstate = "Candidate for terraforming":
            terraformable
        |elif reportbody.terraformstate = "Terraformed":
            terraformed
        }
    }
```
(Or just that one line of "Candidate....").  This works perfectly for me, reporting all terraformable worlds when scanned.

**Comment by mearmortal** [comment]
Thanks, that's gone in fine as expected, I will look out for it on my next scans. Thank you.

**Comment by mearmortal** [comment]
Nice one, that word fine. Thanks.

**Comment by Tkael** [comment]
Yep. This will be updated in a future release.
