### ISSUE TITLE
Feature Request - turn off update warning

### ISSUE THREAD

**Issue by MalicT** [EDCD/EDDI#1244]
## EDDI version in which issue found
3.3.4

Every update since 3.3.4 has had the side effect of some kind of looping code, and makes EDDI completely unusable when used as a plugin for Voice Attack.

As I am streaming to 200-300 average viewers, and around 2,000-3000 unique visitors each day, to have to keep shutting down VA because the EDDI plugin is causing the CPU to use 80% of my CPU is extremely annoying.

Trying to do a quiet reboot/repair of VA and EDDI has to blast with the EDDI VERSION 3.3.6 IS NOW AVAILABLE PLEASE SHUTDOWN VOICE ATTACK AND RUN EDDI STANDALONE TO UPGRADE each time.

Can you please add an option to have EDDI *NOT* check for updates every time it is started up.  Sometimes a working program that is required for VA abilities to function would be much more preferred to have over a program that visibility slows a computer during a live-stream to slow to a crawl. 

https://github.com/EDCD/EDDI/issues/1194
https://github.com/EDCD/EDDI/issues/1243

https://i.imgur.com/RMllXRJ.png
https://i.imgur.com/jdw1oCG.png

**Comment by richardbuckle** [comment]
No.

**Comment by richardbuckle** [comment]
The update warning is required in order to retain the ability to pull a version of EDDI that submits in a format that is no longer supported by EDDN etc.

**Comment by MalicT** [comment]
Then can you make sure that the updates _work_ and do not cause it to make other programs use 80% of the CPU before you release it?

https://github.com/EDCD/EDDI/issues/1243

**Comment by Tkael** [comment]
For us, it has been working. We're still trying to establish what it is about your configuration that is creating this cpu spike.

We have to rely on beta tests to report issues that we don't observe ourselves. We can't address issues before we've been made aware of them. 

We understand that this is a frustrating situation. We're not discounting the underlying issue here. We want to fix it.

The more help you can give us in replicating the issue, the more certain we can all be that the issue will be resolved for the next release.
