### ISSUE TITLE
Does not recognize my voice

### ISSUE THREAD

**Issue by wopablillo** [EDCD/EDDI#1288]
## EDDI version in which issue is found
3.4

## Steps to reproduce
1. Opened eddi
2. I use it as a standalone with no other voice program running, I do not own VoiceAttack
3. Link with API 
4. Start Elite Dangerous
5. Start game

## Expected
EDDI recognizes my voice

## Observed
EDDI tells me the current status of my missions, but does not recognize my voice and I can not do anything else

## Investigation
I am a Spanish speaker

**Comment by Tkael** [comment]
Normally, users use VoiceAttack with EDDI if they want to execute commands via speech. EDDI is not designed to provide voice recognition services. It is designed to respond to in-game events with text-to-speech and to provide appropriate variables so that you can bring to the surface the information you care most about.
