### ISSUE TITLE
Sometimes event ((EDDI docked)) does not work

### ISSUE THREAD

**Issue by nepomuk16321** [EDCD/EDDI#1307]
## EDDI version in which issue is found
EDDI Version 3.4.0

## VoiceAttack version in which issue is found (as applicable)
VA Version 1.7.5 and beta 1.7.5.12

## Steps to reproduce
Last night and this morning, on the last approaches, the event ((EDDI docked)) was not recognized. The event ((EDDI docking granted)) was detected !

## Expected
Recognize the Voice Attack EDDI event and entry into the Voice Attack LOG window

## Observed
Is it possible that case sensitivity is a problem?

## Investigation
[eddi.log](https://github.com/EDCD/EDDI/files/3197551/eddi.log)
[eddi3.log](https://github.com/EDCD/EDDI/files/3197560/eddi3.log)

**Comment by nepomuk16321** [comment]
Addition: The event ((EDDI station no fire zone exited)) is also not recognized by VA.

**Comment by nepomuk16321** [comment]
Correction: The problem only occurs if you want to land at the same station (no supercruise) !!!

**Comment by Hoodathunk** [comment]
@nepomuk16321 are you running 3.4.0 or a build of the latest #develop branch?

**Comment by Hoodathunk** [comment]
Ok, re-reading your last comment... if you're docking, undocking and then trying to re-dock at the same station with no jumping (supercruise or otherwise) in between, that is currently normal behavior and has been that way since jgm was managing the project.

Good news is that the next beta has added additional states, `docked` and `landed` which will allow EDDI to track repeated docking at the same sation.

**Comment by Tkael** [comment]
Will be resolved by commit# 281a9bedcad15cf15e7f530009c1bcd1c08a7fd1.

**Comment by nepomuk16321** [comment]
Thank you for your information !

**Comment by Tkael** [comment]
Merged.
