### ISSUE TITLE
{TXT:Ship size} isn't reporting respective size.

### ISSUE THREAD

**Issue by bronney** [EDCD/EDDI#136]
## Steps to reproduce
I use the following command in VA while inside an Anaconda:

Begin Text Compare : [{TXT:Ship size}] Equals 'Small'
    Say, 'Small'  (and wait until it completes)
Else If Text Compare : [{TXT:Ship size}] Equals 'Medium'
    Say, 'Medium'  (and wait until it completes)
Else If Text Compare : [{TXT:Ship size}] Equals 'Large'
    Say, 'Large'  (and wait until it completes)
End Condition - Exit when condition met

## Expected
Say Large

## Observed
She said Medium

## Investigation
In fact she says medium for everything, I tried in a Sidewinder, Type-7, etc.

Btw thanks for reactivating the ((docked)) when log in :)

**Comment by Tkael** [comment]
Was your connection to the Frontier API operational at the time?

**Comment by Hoodathunk** [comment]
I've swapped to various sized ships and it's working fine for me.

Additionally, you can use:
`Say, '{TXT:Ship size}'`

To accomplish the same test

**Comment by bronney** [comment]
Oh thanks Hoodathunk.

Tkael,
 
My Frontier API isn't operational, I tried 20 times in the past 5 days since 2.4 it always reset back to the login after entering confirm code.  For some reason, since yesterday I got the ((docked)) back when log in but never gotten it when it was operational.  I also tried clicking "reset" at the bottom of the Frontier API tab.  No difference.  Let me try reinstalling it I guess.

**Comment by Tkael** [comment]
reinstalling won't make a difference. The problem is on Frontier's end. Despite patch notes claiming a fix, a substantial number of commanders still can't connect. Frontier continues to investigate.
The API is, at least for the time, the primary source for information on your current ship. more and more detail is being added to the journal though and as it's added we need to reduce reliance on the API for this information.

**Comment by bronney** [comment]
Thanks for the good work dude.  I have to be patient then.
