### ISSUE TITLE
Variable for remaining jumps?

### ISSUE THREAD

**Issue by rosscarlson** [EDCD/EDDI#1389]
## EDDI version in which issue is found
Current

## VoiceAttack version in which issue is found (as applicable)
Current (not integrated)

Question - and if this is the wrong place my apologies - is there a variable I can read for jumps left in my currently plotted route?

**Comment by Hoodathunk** [comment]
The Discord Channel is the preferred venue for questions as the GitHub ‘Issues’ page is reserved for problems/errors.

But since you are here, the answer is “it depends”. If you’re referring to course plots within ED, then no... The journal does not provide that data.

If you’re looking for a best guess ‘approximation’, based current fuel, ship mass, drive efficiency, etc (basically same calcs that Coriolis does), EDDI provides some functionality via the `JumpDetails()` function within the speech responder scripts. It’s also accessible via a Voice Attack external plugin function call.

All this requires some speech responder/ Cottle and/or VA command scripting experience. The Cottle Help/Variables window provides examples to use the `JumpDetails()` function and there’s a bunch of helpful folks in the community.

**Comment by Hoodathunk** [comment]
Actually, `JumpDetails()` might not give you what you’re looking for, EDDI has the functionality. You would need to use `RouteDetails()` to set your destination within, EDDI. Then the `Jumped` event script will tell you the best guess, `max jumps` remaining.

**Comment by Tkael** [comment]
Closing as answered (@Hoodathunk and I will be notified if you comment here again).

**Comment by rosscarlson** [comment]
Thanks for the detail - next time I'll ask in the Discord!!
