### ISSUE TITLE
Route destination is completely incorrect

### ISSUE THREAD

**Issue by arancaytar** [EDCD/EDDI#1431]
## EDDI version in which issue is found
v3.4.1.

## VoiceAttack version in which issue is found (as applicable)
-

## Steps to reproduce
1. Plot a route in the Galaxy Map
2. Jump to the next system along the way

## Expected
EDDI announces "Distance to {route destination} is {distance}, with {jumps} jumps remaining"

## Observed
The actual announcement names a completely different system that isn't the destination, and which I've never visited or plotted a course to. In this case it is stuck at the system `LP 390-16`. The distance also matches that system, rather than the actual destination.

The value of the `{event.destination}` variable is somehow set to this value instead of the actual route destination, and it doesn't change if a new route is plotted either.

Edit: The `LP 390-16` destination is still announced even if the route is cleared entirely.

**Comment by Tkael** [comment]
The route destination that EDDI is referencing is set via the RouteDetails() function (https://github.com/EDCD/EDDI/wiki/Help#routedetails). You must use that function to update your route.

Simply plotting a new route on the Galaxy Map will not change the route set in EDDI, nor can it (since no information is written to the journal about your route or destination when you plot a course in the Galaxy Map).

**Comment by Hoodathunk** [comment]
To add to Tkael’s commentary, the destination set by EDDI comes from navigational aids built into EDDI for mission and misc services routing. With manual intervention, it can be made to match a plot in the galaxy map, but FDEV does not provide the necessary data to automate it.

**Comment by Hoodathunk** [comment]
Closing this issue. Be aware that any further comments/questions can still be posted and seen by the dev team.

**Comment by arancaytar** [comment]
Sorry, thanks for the info; I incorrectly assumed this was part of the data received through the Frontier API. :)
