### ISSUE TITLE
Enhancement Suggestion: Enhance the "F('scriptName')" function to allow parameter passing

### ISSUE THREAD

**Issue by Loophole62ndFF** [EDCD/EDDI#1462]
## EDDI version in which issue is found
3.4.3

It would be a great enhancement to the scripting language if the (sadly undocumented) {F('scriptName')} function was extended to allow arguments to be passed in to the target script.

This would be a powerful feature, and could allow for more code re-use, fewer global variables needed and simpler scripts.

E.g. when the 'Message Received' script speaks a message, it could invoke a voice-selection function to assign speaker-specific voice like so:

From {event.source} {event.from}. {Transmit(Voice(event.message,F("SelectVoice",event.source,event.from)))}.

There are many other possibilities where argument-passing could be beneficial.

On the receiving script side, any arguments could be exposed as an 'args' array, or as preset variables 'arg1', arg2' etc that default to an empty string.

**Comment by Tkael** [comment]
This has the risk of complicating the scripting process (something that quite a few users already find a bit daunting). What advantages do you see to this approach vs. the current approach (using SetState)?

**Comment by jwvanderbeck** [comment]
As a developer I would argue that passing arguments is far less complex and easier to read than setting global variables.

I agree that the scripting process in EDDI is daunting but mostly because the language is very weird and non-standard.

**Comment by Hoodathunk** [comment]
Yes, Cottle is 'non-standard' and it doesn't have the complexity and 'finesse' of robust, advanced languages, but it is particularly suited for this primarily TTS application.

As one of three team members, I will speak for my self in saying that since the vast majority of the EDDI community uses the default scripts (or very minor variations), improving the script editing or adding programming functionality to Cottle beyond access to new FDEV data sets is low on my priority list. The cost-benefit ratio (compared to other features requested by the community) is just not that great.

That said, we would be most happy to evaluate contributions to the code base, in this realm.

**Comment by jwvanderbeck** [comment]
>  vast majority of the EDDI community uses the default scripts (or very minor variations), improving the script editing or adding programming functionality to Cottle beyond access to new FDEV data sets is low on my priority list. 

Fair point.  I think we can live without parameters unless they are super simple to add.  I was merely pointing out that in my opinion they make things easier, not harder, to understand.

**Comment by Hoodathunk** [comment]
I don't disagree.

**Comment by richardbuckle** [comment]
I would like to add that [the Cottle docs](http://r3c.github.io/cottle/) do describe in section 4.4 how local functions with parameters can be defined. That will meet a lot of needs. 

As to passing function parameters between scripts, I have to concur that I am leery of over-complicating our C# code-base for it at this point.

We do have #1032 to support code coloring for Cottle, and in the meantime there is a Notepad++ plugin for it courtesy of StivlWrith: https://forums.frontier.co.uk/threads/udl-eddi-scripts-for-notepad.467432/
