### ISSUE TITLE
Material Monitor reports 0 for all Guardian Materials.

### ISSUE THREAD

**Issue by antrys** [EDCD/EDDI#1516]
## EDDI version in which issue is found
3.4.3

## VoiceAttack version in which issue is found (as applicable)
1.7.8

## Steps to reproduce
Pick up any Guardian material with your cargo scoop on SRV.

## Expected
EDDI inventory levels to increase to match ED inventory levels.

## Observed
EDDI **DOES** report that the material was gathered (I get a report that says "zero" on each pickup)
All Guardian Materials stay at zero.

## Investigation
Have tried restarting ED with both VA and EDDI standalone open to try and reload the API data: No effect.  EDDI standalone guaudian materials are all zero.
I'm thinking that perhaps they've changed the format of the guardian data in the API?  Or there's a typo in the way it's parsing the API output?   Should be a pretty minor fix.  Only happens with Guardian materials.

Note: INARA does report guardian material levels correctly, so the API is working......

**Comment by Tkael** [comment]
Odd. Please provide the following:
1. The journal .log file from the applicable game session (located at `[your Saved Games folder]/Frontier Developments/Elite Dangerous/`) 
2. EDDI's log file from the applicable game session (if you've launched EDDI more than once since reporting, it might be eddi1.log, eddi2.log, etc.), found at `%appdata%/Roaming/EDDI`

**Comment by antrys** [comment]
Well apparently this is one of those issues where all I have to do is open a ticket and fixes itself to make me look like an idiot. doh!

Magicitastially started working.  thx.

**Comment by Tkael** [comment]
These are the best kinds of issues in my opinion. ;-)
o7 commander
