### ISSUE TITLE
Roll back fallback ship description

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1608]
A well-meaning attempt to expand the default of "your ship" if the Cmdr hadn't named their ship into "your Cobra" etc fell afoul of language grammer rules. It's better just to ditch the concept and go back  to just "your ship".

**Comment by Tkael** [comment]
That's close but not entirely accurate. The original was hard coded to an English string... "your [ship model]" rather than "your ship". "Your ship" was only used if `SpokenModel()` was null.

WAS:
```cs
        public string SpokenName(string defaultname = null)
        {
            string model = (defaultname ?? SpokenModel()) ?? "ship";
            string result = ("your " + model);
            if (!string.IsNullOrWhiteSpace(phoneticname))
            {
                result = "<phoneme alphabet=\"ipa\" ph=\"" + phoneticname + "\">" + name + "</phoneme>";
            }
            else if (!string.IsNullOrWhiteSpace(name))
            {
                result = name;
            }
            return result;
        }
```
Using translations of "your ship" rather than "your Cobra" or "your Fer-de-lance" alters the result that English speaking users will hear.

Either
1. we switch to a more generic "your ship" across the board (this is easier to implement / translate but in my opinion it also somewhat degrades the feature).
2. we allow translators to designate each ship model's possessive "your" for their language and apply the correctly gendered "your" from those translations.
