### ISSUE TITLE
EDDI v3.5.1 accessing Ship monitor tab crashes EDDI.

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#1617]
## EDDI version in which issue is found
3.5.1
## VoiceAttack version in which issue is found (as applicable)
Both standalone and VA 1.8.2
## Steps to reproduce
1. Open EDDI standalone or run config from VA
2. Click Ship Monitor Tab

## Expected
See ship monitor configuration panel

## Observed
EDDI silently crashes. No log entries in _eddi.log_

## Investigation
Noticed all my phonetic ship names were not being used. That is why I first accessed the ship monitor panel. Tried erasing _shipmonitor.json_ and letting EDDI rebuild it. Still Crashed when accessing the ship monitor tab, although there was a new _shipmonitor.json_ file created.
Erased **all** of the EDDI configuration files (moved _appdata/eddi_) and restarted fresh standalone. Crashes still when accessing ship monitor tab.
Note: While under VA - Crashes VA also.

Reverted to EDDI v3.5.0 - working OK. (Ship monitor phonetic names were wiped by EDDI v3.5.1 and I had to restore names from a backup text file I keep.)

**Comment by Tkael** [comment]
Confirmed. Looks like there was a bad merge. I've submitted PR #1621 with the fix.

**Comment by rodan123** [comment]
Glad the issue was as simple as a typo.
I applied the change to my build and the crashing issue when accessing the _Ship monitor_ tab has been resolved.
However, installation of EDDI v3.5.1 over v3.5.0 does **still clear all of the ships phonetic names.**
If this is expected behavior, there is no mention of it in the change log. A note to backup the phonetic names before installation of this version would have been helpful. Luckily I did have a backup and didn't have to redo the half dozen phonetic spellings that I have.

Thanks for the quick response and fix, though. Great work on the program.

**Comment by Tkael** [comment]
That was my bad. Had we anticipated the effect on the JSON file, we would have included an appropriate note in the change log. It was an oversight on my part. I've submitted a new PR (#1624) to maximize the backwards compatibility of the next release with prior versions but unfortunately it won't be able to restore any settings lost while using 3.5.1.

If PR #1624 is accepted then any phonetic name recorded using version 3.5.1 will be discarded. That said, since selecting the shipmonitor tab currently crashes EDDI I expect that for most users the changes to ship phonetic names under version 3.5.1 have been minimal and that reverting to using the same property name as under prior versions is the best course for maximizing compatibility with prior versions. I'm sorry for the inconvenience this is causing.
