### ISSUE TITLE
Improve documentation of object data passed to VoiceAttack

### ISSUE THREAD

**Issue by MalicT** [EDCD/EDDI#1627]
3.5.1

## Expected
Pass hotspots variable to VA so can use VA to give audio alerts of void opals or such are in the ring when ((EDDI ring hotspots detected)) event is triggered https://github.com/EDCD/EDDI/wiki/Ring-hotspots-detected-event

## Observed
hotspots variable is not passed to VA accessible variable

**Comment by Tkael** [comment]
Generally, we advise letting EDDI speak and VoiceAttack act since we believe that sort of setup best plays to the strengths of each. 

That being said, the wiki is not comprehensive and doesn't fully document object data being written to VoiceAttack. You would see additional values being set for object data if you were to watch EDDI's log with verbose logging enabled. I believe the data you seek is already available, albeit not fully documented.

Please test the following variables (where *n* is the zero-based indexed hotspot number): 
> {TXT:EDDI ring hotspots detected hotspots *n* commodity} 
> {DEC:EDDI ring hotspots detected hotspots *n* amount}

The true solution to this issue, and others to like it, will probably be to update our wiki auto-generation code to better handle object data.

**Comment by MalicT** [comment]
EDDI is far too chatty for streaming and is why I have VA commands set to have it respond only when asked or audio alerts that are not intrusive and speaking over me.  Have made some edits to the ((EDDI ring hotspots detected)) and have set up some audio beeps if the hotspot you are looking for is present now

**Comment by Tkael** [comment]
I take it that the variables I suggested above worked then. ;-)

**Comment by MalicT** [comment]
Yes, have been able to get it to identify and give audio alerts for different materials, just working on fleshing the VA commands out more
