### ISSUE TITLE
eddi unable to start 

### ISSUE THREAD

**Issue by djhandy** [EDCD/EDDI#1684]
## EDDI version in which issue is found
3.5.2

## VoiceAttack version in which issue is found (as applicable)
1.8.3

## Observed
when trying to run eddi nothing would happen no gui and does not appear in the task manger 

## Investigation
i have tried uninstalling and reinstalling (same issue)
removing all eddi from %appdata%. it would create the folder but it had no files in it 
tried installing voice attac. voiceattack tried to run it and agian nothing would happen but it would install the file in the %appdata% folder  i tried deteling the files again and just run eddi without voiceattack and still nothing no files and gui 
with voiceattack open i tried to open it but i get the error message say cant open more then one instance 
tried to unstalling both voice attack and eddi and just installing eddi and getting the same problem

the log file attached is from when i tried to open it with voiceattack 

thank you 
[eddi.log](https://github.com/EDCD/EDDI/files/4067328/eddi.log)

**Comment by Tkael** [comment]
The log seems to shows that EDDI was running fine under VoiceAttack and ran for about 15 minutes before exiting cleanly when VoiceAttack closed. 

You're probably already aware but EDDI is configured to run with its main window hidden when it's running as a VoiceAttack plugin and that you need to invoke the UI with a command, but if not then there are more details [here](https://github.com/EDCD/EDDI/wiki/VoiceAttack-Integration on how to do that.

Since the log under VoiceAttack doesn't show anything unusual, it's difficult for me to speculate on why standalone mode apparently isn't working for you without an appropriate log for that mode. 

- If you try to open EDDI in standalone mode and then open the task manager, is there an EDDI process running?
- If you try to open EDDI in standalone mode a second time, does a message box appear that says that EDDI is already running?
- Can you please provide a log from standalone mode?
- Is Elite already running when you try to run EDDI in standalone mode? If you log into Elite Dangerous (without EDDI running) then try to open EDDI once you're in your ship does that make a difference?

**Comment by Tkael** [comment]
I'm closing this due to lack of response, but can re-open it again if you respond later.
