### ISSUE TITLE
Theme changes [Feature Request]

### ISSUE THREAD

**Issue by benjamenhogben** [EDCD/EDDI#1688]
Hi all,

I'm currently working on some new styling for the application - I've not worked in c# projects before so it's been a bit of a learning curve so far working out the tooling

I've worked out a relatively simple way of changing/tidying up the theming of the application and its projects by utilising the WPF .xaml files and was really looking for guidance/feedback

my fork is here if you want to check it out/qa it/work on it: https://github.com/benjamenhogben/EDDI/tree/feature/update-theme

I've added global styles here: https://github.com/benjamenhogben/EDDI/blob/feature/update-theme/EDDIStyling/GlobalStyling.xaml
and added them to each project referenced as a resource dictionary - tidying up as necessary (mainly removing a lot of background colour properties)

The project I seem to be struggling with the most is the InaraResponder project - it doesn't seem to apply the resource dictionary at build time - I'd be really appreciative of any guidance on that on in particular :)

There are still a few bugs to be ironed out but I'm running out of steam a little and not even sure if I'm doing it the right way tbh! Any help appreciated :)

**Comment by Tkael** [comment]
We'll have to check it out. 🙂
What are your goals with the revised styling?

**Comment by benjamenhogben** [comment]
screenshot of progress - there's a fair bit done so far: https://imgur.com/a/rlM6ghl

**Comment by Tkael** [comment]
I like the idea of having a standard style library, though of course EDDI doesn't need to match the styling of coriolis/inara.cz. ;-)

Other miscellaneous feedback:
- The default window size is just small enough that a scrollbar appears. Either margins or the window size needs adjustment to prevent this.
- Links are inconsistently styled between the `EDDI` tab and the responder / monitor tabs. The blue links are particularly difficult to read on a dark background.
- The white background for the datagrids doesn't look great with the dark theme
- At the default window size, text is cut off on some buttons (particularly on the Material Monitor tab). Text will be cut off even worse for some other non-English languages (e.g. German).
- In the `Ship Monitor` tab, the `Role` string is centered while all other columns have their contents aligned to the top of the cell. Likewise in the `Speech Responder` tab, text is "Top" aligned while buttons and similar are all "Center" aligned so button text is not in-line with normal text.
- Buttons inconsistently highlight on mouse hover. No highlight for the `Frontier API` tab, the `Export it` button on the `Ship Monitor` tab, or the `Reset` buttons in the `Speech Responder`.
- Buttons are very large, particularly in the `Speech Responder` where they consume a lot of vertical space and where they cut off a significant portion of the script description.
- The `Voice` dropdown in the `Text-to-Speech` tab probably ought to be right aligned like the other properties below it rather than center aligned. ;-)
- Project references to EDDIStyling.csproj can be safely removed - they are not being used. e.g.
```xml
    <ProjectReference Include="..\EDDIStyling\EDDIStyling.csproj">
      <Project>{a3e8f349-d621-4bdd-b70a-b29832323402}</Project>
      <Name>EDDIStyling</Name>
    </ProjectReference>
```
- 👍 GlobalStyling.xaml does really seem to have some nice potential for easily altering styles across the UI. 
- 👍 You seem to have solved an issue we were having when using virtualization in the `Speech Responder` datagrid. Whatever else we decide about this theming project, I'll need to look into your implementation there more deeply. ;-)

**Comment by Tkael** [comment]
If you don't mind, I'd like to ask you to pause work on this branch until the rest of the team has had a chance to review.

**Comment by Tkael** [comment]
I've spent some more time examining your branch in more detail this evening and I'm finding a number of colors that you've hard coded to match your preferred theme. If the intent is to make a flexible style library that can accept a wide variety of themes then hard coding specific color preferences like that is not acceptable.

**Comment by Tkael** [comment]
While this is an interesting proof of concept, there are still issues with your branch that need to be resolved before we could consider incorporating your changes. 
- A theming engine should maintain the current style as a default and add support for additional styles rather than replacing the current default style with a new style. 
- Elements (for example, the window tabs) must not be hard coded to a particular style.

Since we've provided the feedback you've requested I'm going to go ahead and close this as resolved. o7 commander!

**Comment by benjamenhogben** [comment]
Ok - so does that mean I can continue on the feedback above if I abstract out the styling?

There should be some capacity to do so in globally defined templates

**Comment by Tkael** [comment]
I can't speak for the rest of the team but I'd be willing to take another look at it at that point.

**Comment by dylan-k** [comment]
Just posting here to voice support for anything like a "night mode" for EDDI. Space is dark out there.

**Comment by Tkael** [comment]
While I appreciate that theming or a night mode might be a "nice to have" feature, EDDI's primary interface with users is typically via audio and we feel like our time as developers can (at least for the time being) be better spent on our other open tickets. 

Pull requests are welcome (subject to the guidance in https://github.com/EDCD/EDDI/blob/develop/docs/Contributing.md).

**Comment by benjamenjohnsondev** [comment]
> Just posting here to voice support for anything like a "night mode" for EDDI. Space is dark out there.

Ageeed. Some of us use second screens and having this open is blinding

@Tkael I did look into building a theme switcher but it isn't feasible imo. I'd be willing to take a look at this again and update the theming for the panels...

My theme does look better than the default eddi... Which is why I still use it over the this one 😅
