### ISSUE TITLE
Phonetic EDDI personality (ICAO for EDDI module grades)

### ISSUE THREAD

**Issue by benjamenhogben** [EDCD/EDDI#1689]
Hi,

I've added a new json file for a "Phonetic EDDI" personality - it uses the EDDI personality nearly exclusively but adds phonetic pronunciation for the modules

I was wondering how I can register it as a new personality? Or is it enough to add it as a json file?

Branch [here](https://github.com/benjamenhogben/EDDI/tree/feature/new-personality)

**Comment by Tkael** [comment]
Do you have a list of modules and accompanying phonetic pronunciations? If so, we might consider implementing using a different approach.

**Comment by benjamenhogben** [comment]
@Tkael no I don't - I've just used the available cottle P() method wherever the module grade is in the template strings - there may be more instances but I've yet to find them

Converts something like "fuel scoop 5a" to "fuel scoop 5alpha"

**Comment by Tkael** [comment]
Ok... so scripts are simply being updated to wrap the module grade in `{P()}`, no other changes. The following scripts are updated in the subject branch:
- Module purchased
- Module retrieved
- Module sold
- Module sold from storage
- Module stored
- Module swapped
- Module transfer
- Modules stored

Why create an entirely new personality for this rather than submitting the change to eddi.json?

**Comment by benjamenhogben** [comment]
So that it's optional to the user rather than the default - users may now be used to the "5a" pronunciation - happy to submit as a default personality change though as I think it sounds better anyway
