### ISSUE TITLE
Announcement of hotspots at the start of the game

### ISSUE THREAD

**Issue by nepomuk16321** [EDCD/EDDI#1697]
## EDDI version in which issue is found
EDDI v.3.5.2

## VoiceAttack version in which issue is found (as applicable)
VA v.1.8.2

## Steps to reproduce
1.) I have mapped a ring
2.) Announcement that the ring has been mapped is done.
3.) Game over.
4.) New start of the game. Announcement that the ring was mapped came back.

## Expected
[Describe what you expected to happen]

## Observed
A rather unimportant problem. When I start the game, the announcement comes up that I have found hotspots. That's also true but that was a few stations ago. Should this announcement come with the start of the game ?

## Investigation
I assume that the script "Ring hotspots detected" is started with the event "Loadout" or "Location".
[eddi-log.zip](https://github.com/EDCD/EDDI/files/4148691/eddi-log.zip)
I have also observed the behaviour of the original character.

**Comment by Hoodathunk** [comment]
A -'non-verbose' EDDI log is of limited use, but the Journal Log file for that session will likely be more helpful to you.

@Tkael is the expert here, but I expect you'll find a `SAASignalFound` event, immediately following the startup events, due to logging on, in the vicinity of the hot spot.

At present, the script does not filter this particular scenario.

**Comment by nepomuk16321** [comment]
:-) 
Yeah, you're absolutely right. I searched the journal. There's a SAA signal in the system where I am right now. It's also being read correctly. And since it hasn't been filtered out yet, the find is announced. Is that right? Then the issue could be closed.

**Comment by Tkael** [comment]
Yes, it's triggered by simple proximity. This is functioning as intended.
