### ISSUE TITLE
Bodies to map

### ISSUE THREAD

**Issue by Timnus** [EDCD/EDDI#1723]
## EDDI version in which issue is found
3.5.2
## VoiceAttack version in which issue is found (as applicable)
N/A
## Steps to reproduce
1. scan a body in a system

## Expected
cannot turn off "bodies to map" do not want it to verbally report that. Checked box wont allow un-select.

## Observed
Works as programmed.

## Investigation
tried shift-click, alt-click, ctr-click. cannot get it to un-select.

**Comment by Tkael** [comment]
This is explained by the text linked in the upper right corner of the speech responder ("Read about the speech responder's functions [here](https://github.com/EDCD/EDDI/blob/develop/SpeechResponder/SpeechResponderHelp.md)").

> 
> The speech responder contains both event-based and non-event-based scripts. 
> 
> Event-based scripts can be disabled but cannot be deleted. They can also be assigned to differing priorities, as noted below:
> 
> 1 - high priority, interrupts other speech 
> 2 - high priority 
> 3 - default priority 
> 4 - low priority 
> 5 - low priority, interruptible by any higher priority speech 
> 
> Non-event-based scripts must be invoked, either by using a function call from another script or via the VoiceAttack plugin. Since they must be invoked they can be deleted but can neither be disabled nor assigned to new priorities. If invoked by another script, they will take on the priority of the invoking script. If invoked from VoiceAttack, they will use the default priority unless a new priority is assigned via the VoiceAttack plugin, as documented in https://github.com/EDCD/EDDI/wiki/VoiceAttack-Integration.

`Bodies to map` is an non-event-based script which is invoked from the `Discovery scan` script and consequently cannot be disabled directly. You have several options:
1. Edit or disable the `Discovery scan` script
2. Edit and clear the `Bodies to map` script
3. Change your ship's role. By design, EDDI's default personality only recommends bodies to map when your ships role is either "Multipurpose" or "Exploration".

**Comment by Timnus** [comment]
please tell me how to change the ship role and where to read about it

**Comment by clinkingdog** [comment]
@Timnus change the ship role in the Ship Monitor tab. The drop-down list there contains a bunch of different values. (I'm not aware of any documentation of the exact consequences of each of these values, but the examples I know about make sense.)
