### ISSUE TITLE
no voice in game

### ISSUE THREAD

**Issue by UglyRossi** [EDCD/EDDI#1755]
## EDDI version in which issue is found
3.5.2

## VoiceAttack version in which issue is found (as applicable)
i dont use voice attack, eddi only

I installed the EDDI and the speech voice are ok inside the eddi, the tests works 100%, API frontier connected, EDSM and INARA conected too. My problem, there is no voice in game, no reports when i scan, nothing. My ED journal are in the default folder.

I tryied a lot of configurations, even a clean reinstall of eddi, the test voice are ok in eddi but dont work with the game.

**Comment by Tkael** [comment]
Please share a screenshot of the Speech responder tab in EDDI's UI so that we can see how things are configured?
Please also verify that the game is writing data to `[Your saved games folder]/Frontier Developments/Elite Dangerous/`?

**Comment by UglyRossi** [comment]
speech responder and text-speech screens

![eddi](https://user-images.githubusercontent.com/64656654/80833003-1297a380-8bc4-11ea-839e-3cb00f447e22.jpg)
![eddi2](https://user-images.githubusercontent.com/64656654/80833005-13c8d080-8bc4-11ea-8c4b-c07a6227ea95.jpg)

**Comment by Tkael** [comment]
Ok, nothing jumps out there. Can you attach a .zip of your recent log files?

**Comment by UglyRossi** [comment]
> Ok, nothing jumps out there. Can you attach a .zip of your recent log files?

Where can i find?

**Comment by UglyRossi** [comment]
[eddi1.zip](https://github.com/EDCD/EDDI/files/4566109/eddi1.zip)


You mean this logs?

**Comment by Tkael** [comment]
Yes. 

No exceptions / errors were logged during the session.

It looks like Elite was already running when EDDI was started. When that occurs, EDDI silently loads the events from from prior to it starting so that it can gather the state info it needs (This only took about 3 seconds).

I see several `Ship fsd` events after EDDI finished loading but the Speech Responder has no default script for that event so that wouldn't have triggered any speech. I don't see any other events that were recorded from in-game activity between the `Ship fsd` events and EDDI stopping.

Please re-test in-game while performing a wider variety of actions?

**Comment by Tkael** [comment]
Closing due to lack of feedback and possible duplication with #1758.
