### ISSUE TITLE
Feature Request - Add mining events

### ISSUE THREAD

**Issue by MalicT** [EDCD/EDDI#1782]
## EDDI version in which issue is found
3.5.2

## VoiceAttack version in which issue is found (as applicable)
1.8.5

## Steps to reproduce
Does not exist

## Expected
(((EDDI asteroid cracked event)))

## Observed
does not exist

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
Yes, we should add mining events. From the player journal:
- `AsteroidCracked`
- `ProspectedAsteroid`

It hasn't been a high priority because the events are very sparse in information:
- `AsteroidCracked` tells us the name of the nearest current body. No other details, including the motherload for the asteroid just cracked.
- `ProspectedAsteroid` provides a little more detail (Composition, Motherload, Materials, & %remaining) but gives us no way to tie the data to the `AsteroidCracked` event and be sure the data for `AsteroidCracked` would be correct.
