### ISSUE TITLE
Warning of low fuel after jump despite having near full fuel

### ISSUE THREAD

**Issue by zcampau** [EDCD/EDDI#1790]
## EDDI version in which issue is found
v3.5.3-b1

## VoiceAttack version in which issue is found (as applicable)
n/a

## Steps to reproduce
1. Jump to a new system
2. Voice reads out how much fuel is left

## Expected
Voice only reads out if fuel is low or zero

## Observed
Voice reads out fuel being low or zero even when it is near full

## Investigation
Repeated jump after fuel scooping until full. Issue persists on subsequent jump

[eddi_issue.zip](https://github.com/EDCD/EDDI/files/4693671/eddi_issue.zip)

**Comment by Tkael** [comment]
https://cdn.discordapp.com/attachments/353595704658231299/715451832998166568/unknown.png

Initial observation: The log files seem to be indicating that EDDI is having trouble reading your config files or obtaining your ship details (including the size of your fuel tank). It looks like a divide by zero exception is being thrown when calculating your fuel consumption (which I suspect would be due to EDDI not having the fuel tank size). We'll have to think about what could be going on here.

**Comment by zcampau** [comment]
Last night the issue persisted after exiting and restarting both EDDI and E:D client. Today, the issue no longer occurs. I'll leave it to you to decide whether to close the issue or how you want to handle it. If it happens again I can try to do more troubleshooting.

**Comment by Tkael** [comment]
It's unclear from the logs where the issue started. 

EDDI thought that you were in a ship with a localId of 32 (I'm not sure which ship this may have been... it wasn't logged) while the Frontier API didn't think that a ship with a localId of 32 existed in your shipyard and was correctly reporting that you were in your Dolphin "Euclid" with a localId of 31. 

Without more data about how this mismatch began, I'm not sure that there's much we can do to correct this. Do you still have the logs from sessions prior to these that you can share?

**Comment by Tkael** [comment]
Closing due to insufficent data to determine what caused the ship monitor to enter an incorrect state. If it happens again, please open a new ticket with a verbose log starting from the beginning of your play session. Thanks!
