### ISSUE TITLE
Unable to fully initialize eddi. some functions may not work.

### ISSUE THREAD

**Issue by Jwh1o1** [EDCD/EDDI#1807]
## Steps to reproduce
It just happens randomly when I open Voice Attack. It happend yesterday and i read an issue saying reinstall and when I did it worked yesterday and then today when I started playing again it worked the first time, but when i started voice attack again it did the same error not able to initialize eddi fully

## Expected
I expected voice attack to load everything without an issue.

## Observed
Voice attack was not able to load everything

## Investigation
I did not have this happen until I updated to the newest Voice Attack

**Comment by Jwh1o1** [comment]
[eddi1.log](https://github.com/EDCD/EDDI/files/4738143/eddi1.log)
[eddi2.log](https://github.com/EDCD/EDDI/files/4738147/eddi2.log)
[eddi3.log](https://github.com/EDCD/EDDI/files/4738148/eddi3.log)
[eddi4.log](https://github.com/EDCD/EDDI/files/4738150/eddi4.log)
[eddi5.log](https://github.com/EDCD/EDDI/files/4738151/eddi5.log)

**Comment by Tkael** [comment]
It looks there is a problem loading the configuration file `elite.json`. Please navigate to `%appdata%/Roaming/EDDI` and try removing `elite.json` (if you could share it with us, it's safe to share and we'd be interested in seeing what it looks like).
If for some reason that doesn't get you back on your feet, please follow the full [troubleshooting steps from the wiki](https://github.com/EDCD/EDDI/blob/master/TROUBLESHOOTING.md#eddi-doesnt-start-or-crashes-on-startup).

Please report back once you've completed these steps so that we know that you're back up and running.

**Comment by Tkael** [comment]
Closing as (presumably) resolved. Please reply back if otherwise.
