### ISSUE TITLE
EDDI 3.7.0 Spurious Actions Being Initiated.

### ISSUE THREAD

**Issue by incryptx** [EDCD/EDDI#1885]
Since the 3.7.0 Update, I have spurious (unwanted/ill-timed) actions taking place.

I am running EDDI with VA and several HCS Voicepacks. When in normal space, on a planet, or in an asteroid field, I have landing gear, cargo hatch, silent running and boosting all occurring at spurious moments, sometimes they are ill-timed, like silent running being activated in the middle of combat, or landing gear coming down in the middle of an steroid field, or boosting in a station.

I don't know what causes these actions to occur or whether the HCS voicepack voice variables are in conflict, but to prevent these things from occurring, the only thing I can do is to uncheck the EDDI plugin in VA and run without EDDI.

Essentially, I turned EDDI off. Without EDDI running, the actions of landing gear, cargo hatch, silent running and boosting at spurious times no longer occur.

So, my conclusion is that there are variables generated by EDDI and passed to VA which conflict or inadvertantly activate these functions or events at spurious times. I cannot find any log which I can use to track exactly why these events are occurring, but turning EDDI off seems to solve the issue.

Let me know what I can do to help track this down. It is irritating at best, and destructive in the worst case.

**Comment by Tkael** [comment]
EDDI does not directly trigger any in-game actions via VoiceAttack. What may be happening is that VoiceAttack is recognizing a command (maybe the speech from EDDI is being recognized as a command by your HCS pack) and then VoiceAttack is sending an input to the game. 

There is an option to display the confidence with with a command is recognized by VoiceAttack. You might want to turn that on then tune the confidence interval for your individual VoiceAttack commands so that they do not trigger accidentally (in my case, I find that the "boost" command needs a very high confidence interval).

If you're not using a gaming headset, you should also consider obtaining one to prevent background noises, audio feedback, or in-game audio from triggering spurious commands.

**Comment by Tkael** [comment]
Closing as (presumably) resolved.
