### ISSUE TITLE
Almost every script is erroring

### ISSUE THREAD

**Issue by rakosi2** [EDCD/EDDI#1907]
## EDDI version in which issue is found
[Please give the full version number here, not just "latest" or "current"]
3.7.0

## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]
VoiceAttack was not running/installed

## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]
Don't know why it's happening

## Expected
[Describe what you expected to happen]
I expected the voice to work not to repeatedly say "an exception has been thrown by the target of an invocation" over and over

## Observed
[Describe what happened instead]
says fuel level is at 0%, fuel limit script failed, star system script failed, and several other scripts have failed with the same error.

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]
Uninstalled 3.7.0, deleted %APPDATA%\EDDI and reinstalled 3.7.0 and still happening (this log is from the reinstall). Installed 3.5.3.b7 and working as expected without any exception errors.

**Comment by rakosi2** [comment]
Forgot the log [eddi_issue.zip](https://github.com/EDCD/EDDI/files/4974864/eddi_issue.zip)

**Comment by Tkael** [comment]
Thanks for the report and for the log. It's (at least mostly) not a verbose log so I may still need your help to fill in some gaps.

This looks very similar to #1894 (which seems to have been triggered after loading into the game while in an SRV). When this first began, what were you doing (or what had you been doing up to that point)? Did the errors begin immediately after EDDI started or did they begin occurring at some stage during the play session? Did you start the play session in an SRV rather than in your ship?

**Comment by rakosi2** [comment]
Happens as soon as I join solo and the very first thing I hear is the limpet error then thought I don't have a limpet controller. I have never been in an SRV with EDDI open and just started using it. Had no problems on my first day. I did install voice attack trial after I installed EDDI but I uninstalled voice attack and still had the issue.

**Comment by Tkael** [comment]
Could still fit if you'd started the play session where EDDI was run while in an SRV (since the first thing EDDI does when it starts is read the lastest entries in your player journal).

Let's try following the steps [here](https://github.com/EDCD/EDDI/blob/develop/TROUBLESHOOTING.md) to determine whether the issue is stemming from one of your config files. Please do not delete the files, just move them one at a time. If removing one of your config files resolves the issue then (depending on the file) we may ask you to share that config file with us. Please start with shipmonitor.json (since that is the file suspected in #1894).

**Comment by rakosi2** [comment]
I don't remember ever being inside an SRV with EDDI open but I did have a Planetary Vehicle Hangar with me. In hindsight, I shouldn't have done both at the same time but I removed shipmonitor.json while EDDI was open and stored the Planetary Vehicle Hangar and it seems that it hasn't errored for 15 minutes now. I still have the old files since they were in my recycling bin so I included them along with shipmonitor from 3.5.3. Tell me if you need any other files.
[rakosi2 EDDI error.zip](https://github.com/EDCD/EDDI/files/4976602/rakosi2.EDDI.error.zip)

**Comment by Tkael** [comment]
Ok. Looks like swapping ships may have made a difference but I'm not seeing an SRV "ship" like I was seeing with #1894. In any case, I believe it'll be resolved for the next release by [`7f740d1` (#1905)](https://github.com/EDCD/EDDI/pull/1905/commits/7f740d19d949a99496f8252c3e76036ed4e886af).
