### ISSUE TITLE
Create event to detect planets where you can race the sun

### ISSUE THREAD

**Issue by Javelias** [EDCD/EDDI#1918]
## Expected

Idea is based on the steam game, https://store.steampowered.com/app/253030/Race_The_Sun/. The goal of the game is not try falling into the shadows.

It involves implementing a detection of how fast a planet/moon spins relative to it's star (not parent planet), so you know how long a day is and use that day length to calculate the surface speed of the equator. If it is not too high, you can chase after the sun with your SRV.

Not sure if related to https://github.com/EDCD/EDDI/issues/1490, since fast rotation there is likely vs parent body.

## Investigation
CMDR Lyneira found out you can do this mini-game in Elite, for this he created [this spreadsheet](https://drive.google.com/file/d/1XG_b97uuv3iL0kgfpg4MXFqmL31MnIgY/view?usp=sharing), which contains the calculations.

**Comment by Tkael** [comment]
Interesting idea. Skilled commanders (far more skilled than me) can get their SRVs going at some pretty incredible speeds (many hundreds and perhaps even several thousand meters per second) and can even sometimes get their SRVs into orbit. For this to work, we'd essentially need to calculate the ground speed of the sun's shadow then leave it to the commander to determine whether the calculated ground speed is within an acceptable range for that commander (which would suggest that an event might not be the best medium for this). We also can't assume that the commander would need to follow the equator (since the body may be tilted in its orbit) and so we'd probably also need to be able to calculate the heading that the commander would need to follow to observe that ground speed.

The calculations could potentially be accessed via a Speech responder function like `{RaceTheSun(bodyName, systemName)}` or with a VoiceAttack plugin context like `racethesun`.

**Comment by Tkael** [comment]
Note: Star systems with multiple stars may either require more advanced calculations or may not be suitable for use with this proposed mini game.

**Comment by Tkael** [comment]
Here are the applicable formulas from the spreadsheet (with respect to the body):

Solar days (days): 
`(orbitalPeriodDays*rotationalPeriodDays)/(orbitalPeriodDays-rotationalPeriodDays)`

Solar surface velocity (the ground speed of the sun's shadow on the surface) (m/s): 
`(2*PI*radiusKm*1000)/(solarDays*86400)`

The orbital inclination and tilt will affect the heading required to "race the sun" and will cause the appropriate heading to vary throughout the solar year. I don't think a heading can be calculated from the information given.

**Comment by Lyneira** [comment]
My assumption when I thought up this mini game was that you'd pick a planet with a reasonably low tilt relative to the sun and that you would be driving along the equator at a heading of 90 degrees, so I think calculating a perfect heading for the sun can be ignored. In that form, it's entirely about how fast the terminator travels along the equator. :slightly_smiling_face:

**Comment by Tkael** [comment]
It should probably be noted that while it might be useful for EDDI to perform the above calculations, there is nothing preventing you from applying those same formulas right now and adding a "racing the sun" feature to your current personality. ;-)

**Comment by Tkael** [comment]
I've added properties to the `body` object calculating the solar day and solar surface velocity. These will be available in the next release. ;-)
