### ISSUE TITLE
Partial update of carrier commodities on EDDN

### ISSUE THREAD

**Issue by a801227** [EDCD/EDDI#1931]
## EDDI version in which issue is found
3.7.0

## Steps to reproduce
1. List items for purchase on carrier. In my case, I placed 6. (Alexandrite, Bromellite, Grandidierite, LTD, Painite, Void Opal)
2. Launch from carrier and dock.
3. Enter commodities
4. Check EDDN/EDDB for carrier commodity listings after some time.

## Expected
Expected all items to be updated on EDDN.

## Observed
Only 3 items updated. 
![image](https://user-images.githubusercontent.com/12674776/89232447-5374cf00-d59c-11ea-9420-52ab0814d73c.png)
![image](https://user-images.githubusercontent.com/12674776/89232488-638cae80-d59c-11ea-8622-32d9e2f2cfee.png)

## Investigation
EDMC does not have this issue. I am able to see all my carrier listings on EDDN/EDDB after updating.

**Comment by Tkael** [comment]
It looks like [the last EDDN update from EDDI](https://ross.eddb.io/eddn/log/462637046) for the carrier was at timestamp of `2020-08-03T00:10:17.464782Z`, about a day ago. Rather than sending a "partial update", it looks like you simply did not trigger EDDI to send any new update to EDDN with your in-game actions. 

To refresh EDDN, it is not sufficient in EDDI to undock then immediately re-dock. You need to engage the FSD before re-docking (actually engaging it and not just charging it). Would you please try again except making that change to you procedure?

**Comment by Tkael** [comment]
Hi @a801227, were you able to confirm that engaging the FSD before re-docking resolves the issue?

**Comment by a801227** [comment]
Ran into https://github.com/EDCD/EDDI/issues/1552 in the process after my system crashed.
I would suggest adding the solution of cleaning out appdata to "Common Issues".

Back on topic,..
I engaged FSD to supercruise, turned around and went back to redock.
Same issue. Only 3/6 commodities are sent to EDDN.

https://ross.eddb.io/eddn/log/465863421

When I use EDMC, I get this
https://ross.eddb.io/eddn/log/465867019

My market.json

`{ "timestamp":"2020-08-07T17:17:10Z", "event":"Market", "MarketID":3702012928, "StationName":"X9K-WTW", "StationType":"FleetCarrier", "CarrierDockingAccess":"all", "StarSystem":"Gateway", "Items":[ 
{ "id":128668550, "Name":"$painite_name;", "Name_Localised":"Painite", "Category":"$MARKET_category_minerals;", "Category_Localised":"Minerals", "BuyPrice":0, "SellPrice":500096, "MeanPrice":0, "StockBracket":0, "DemandBracket":2, "Stock":0, "Demand":200, "Consumer":true, "Producer":false, "Rare":false }, 
{ "id":128673846, "Name":"$bromellite_name;", "Name_Localised":"Bromellite", "Category":"$MARKET_category_minerals;", "Category_Localised":"Minerals", "BuyPrice":0, "SellPrice":10009, "MeanPrice":0, "StockBracket":0, "DemandBracket":2, "Stock":0, "Demand":100, "Consumer":true, "Producer":false, "Rare":false }, 
{ "id":128673848, "Name":"$lowtemperaturediamond_name;", "Name_Localised":"Low Temperature Diamonds", "Category":"$MARKET_category_minerals;", "Category_Localised":"Minerals", "BuyPrice":0, "SellPrice":500553, "MeanPrice":0, "StockBracket":0, "DemandBracket":2, "Stock":0, "Demand":150, "Consumer":true, "Producer":false, "Rare":false }, 
{ "id":128924330, "Name":"$grandidierite_name;", "Name_Localised":"Grandidierite", "Category":"$MARKET_category_minerals;", "Category_Localised":"Minerals", "BuyPrice":0, "SellPrice":424204, "MeanPrice":0, "StockBracket":0, "DemandBracket":2, "Stock":0, "Demand":100, "Consumer":true, "Producer":false, "Rare":false }, 
{ "id":128924331, "Name":"$alexandrite_name;", "Name_Localised":"Alexandrite", "Category":"$MARKET_category_minerals;", "Category_Localised":"Minerals", "BuyPrice":0, "SellPrice":348192, "MeanPrice":0, "StockBracket":0, "DemandBracket":2, "Stock":0, "Demand":97, "Consumer":true, "Producer":false, "Rare":false }, 
{ "id":128924332, "Name":"$opal_name;", "Name_Localised":"Void Opal", "Category":"$MARKET_category_minerals;", "Category_Localised":"Minerals", "BuyPrice":0, "SellPrice":1014218, "MeanPrice":0, "StockBracket":0, "DemandBracket":2, "Stock":0, "Demand":300, "Consumer":true, "Producer":false, "Rare":false }
 ] }
`

**Comment by a801227** [comment]
I have disabled EDDN updates in EDDI in favor of EDMC due to this issue, hence the long gap since last update.

**Comment by Tkael** [comment]
Ok. I think I understand the issue. It should be resolved by pending PR #1909.

Essentially, we don't use the average price data returned from carriers since that always returns zero (regardless of the real average price in the galaxy). Three of the six commodities had average price data from a source other than this event (where it was zero). We do not currently report commodities to EDDN where the average price is zero (a rule established well before fleet carriers came on the scene), and consequently the three commodities where we had a non-zero average price were reported and the remaining three commodities were not reported.
