### ISSUE TITLE
Suggestion: Removing Galnet for a Radio Station Player.

### ISSUE THREAD

**Issue by incryptx** [EDCD/EDDI#1937]
On the VoiceAttack forum, I have a bug pinned where enabling (checkbox) Galnet in EDDI will cause VA to shut down after a few minutes. The solution was to uncheck Galnet in EDDI. Since Galnet, for all intent and purposes has been discontinued by Frontier, the section in EDDI for Galnet needs to be removed or repurposed.

I wonder if the Galnet section could be repurposed to offer a music player by having some commands in EDDI to play Elite Radio Stations in-game. On Inara, there is a radio station player which could be linked to by EDDI, and calling a URL like:

https://inara.cz/radioplayer.php

I'm sure if EDDI replaced the Galnet code with some code and commands for a radio station player which could be activated by saying something like "Play Radio" or "Play Hutton Orbital", this would be more useful than a disabled Galnet section of EDDI.

Just my suggestion.

**Comment by Tkael** [comment]
It's probably a fool's hope, but I'm hoping that Galnet comes back after the Odyssey update. 

As far as Galnet crashing EDDI, I keep the plugin enabled and haven't been encountering the crash bug that you are describing. Possibly something that was fixed a while ago?

As for a radio station player... I think there are some VoiceAttack profiles out there which already do that aren't there? Do you see any synergies or extra value to be gained from integrating a radio station player into EDDI rather than linking one of the existing radio oriented profiles to your main profile?

As far as a radio for standalone users is concerned... one thing that drew me to EDDI is that it is very good at staying in the background while I'm piloting my ship. To interact with a radio, standalone users would need to have EDDI in the foreground more than they do now. Is that a worthwhile trade-off for standalone users?

**Comment by Tkael** [comment]
Hoping for some Galnet news this coming Thursday. https://www.youtube.com/watch?v=gVcuJ1N8o0o

**Comment by incryptx** [comment]
I'm not holding my breath. Wishful thinking on your part.

But who knows.

**Comment by richardbuckle** [comment]
GalNet is not confirmed as returning, so closing this one.
