### ISSUE TITLE
Question about player faction

### ISSUE THREAD

**Issue by Syrrianyl** [EDCD/EDDI#194]
Hello, this is not a problem, and I know that my question will not depend only on you.
Would it be a good idea (and also a possible idea) that the factions controlled by players can note somewhere a message (why not EDSM?) that would be read when a player enters in a system or a station controlled by that same group . A short message, like tweeter. And also to be able to read it in several languages ​​(Google translate API?)

**Comment by Tkael** [comment]
If EDSM adds a function like that, we can support it. EDSM already does support comments for systems though and that might be enough to serve the same purpose. There's been a bug that's prevented EDSM system comments from being read by EDDI, but I think it should be fixed in the next release (see PR #193).
If you want to make the request directly to EDSM, you can contact them via their Discord [here](https://discordapp.com/invite/0sFOD6GxFZRc1ad0)  or on Github [here](https://github.com/EDSM-NET).
