### ISSUE TITLE
[Suggestion] Update carrier positions on system scan (honk)

### ISSUE THREAD

**Issue by a801227** [EDCD/EDDI#1941]
## EDDI version in which issue is found
3.7.0

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
1. Visit system with carriers
2. "Honk"
3. Look up EDDN for carrier position updates -> Carrier position not updated.

Or
1. Dock with carrier.
2. Relocate carrier to another system
3. Visit target system
4. "Honk"
5. Relocated carrier position still listed in previous system

## Expected
Expected carriers to be updated with new positions if applicable.

## Observed
Carrier positions not updated

## Investigation
This log entry should be enough to update a carrier's position.
{ "timestamp":"2020-08-18T17:05:35Z", "event":"FSSSignalDiscovered", "SystemAddress":7268024264105, "SignalName":"MR BLUE SKY X4T-W3K", "IsStation":true }

**Comment by Tkael** [comment]
EDDI must follow the established schemas for data sent to EDDN. The `FSSSignalDiscovered` event is not permitted by the current schemas. If it were, we would implement it.

To request that it be added to the permitted schemas, visit https://github.com/EDCD/EDDN and open a ticket there (if one does not already exist). 

Please also note that EDDN is managed as a private server with limited power and bandwidth. The server admin may not wish to implement this due to hardware constraints on the current server.

**Comment by Tkael** [comment]
Researching further, I've identified a few other reasons that EDDN may not include the event:

1. Note that the journal event above does not give the MarketId of the carrier/station and the carrier callsign (in this case "X4T-W3K" has been found in some cases to be non-unique). This makes it more difficult for us to be certain that we're looking at the same carrier and not one with a duplicated callsign.

2. The `FSSSignalDiscovered` events are apparently not limited to the carriers that are currently in the system, and may include carriers that have their jump into the system locked in, and carriers that have jumped out recently.

Closing this ticket. There really isn't anything that we can do with this until the issues above have been worked out. o7
