### ISSUE TITLE
Function {Emphasize}, no effect ?

### ISSUE THREAD

**Issue by nepomuk16321** [EDCD/EDDI#1952]
## EDDI version in which issue is found
EDDI v.3.7.0

## VoiceAttack version in which issue is found (as applicable)
no VA

## Steps to reproduce
I am currently reworking script "Docked" for myself.
I would like to have {if event.cockpitbreached: Canopy repair highly recommended.} 
to emphasize the statement.
=> {Emphasize("highly recommended", "strong")}
I play in German. EDDI is also switched to German. The function has already worked in German.
## Expected
strong pronunciation

## Observed
no effect

**Comment by Tkael** [comment]
This is a function that depends heavily on the capabilities of the voice that you are using and its interaction with the native Windows speech synthesizer. What it does is convert the string to include [an SSML "emphasis" tag](https://www.w3.org/TR/speech-synthesis11/#S3.2.2) like `Canopy repair <emphasis level ="strong">highly recommended</emphasis>.` 

Our ability to affect this is limited, but I've tried the same SSML in other applications and had it be more successful there than in EDDI so there's potentially some hope that we can figure this out. 

Why don't you start by telling us what voice you are using so that we can compare notes?

I already know that on my own PC, I have the following results from the current implementation:
| Voice | Result |
|---|---|
| Cerevoice Heather | Emphasis has no perceptible effect. |
| IVONA 2 Amy OEM | Emphasis has no perceptible effect. |
| Microsoft David Desktop | Emphasis slows and slightly increases the volume of the speech. |
| Microsoft Hazel Desktop | Emphasis slows and slightly increases the volume of the speech. |
| Microsoft Zira Desktop | Emphasis has no perceptible effect. |

**Comment by nepomuk16321** [comment]
Okay, if I can help, I will. I am currently using **HARPO Petra 22kHz**. Further installed are **MS David**, **MS Hedda**, **MS Zira** and from **IVONA2 Marlene**. I have only tested Petra. The others I will test and contact you afterwards.

**Comment by nepomuk16321** [comment]
Hello, I have tested my installed voices. Unfortunately I could not find a significant change between the settings "none", reduced", "moderate" or "strong" for the command {Emphasize}. I noticed that the "!" is also only recognized behind "Attention". The voice is raised. It has no influence behind e.g. "Bounty" or "Wanted".

**Comment by Tkael** [comment]
Having found no valid recourse using the `emphasis` tag, I'm now considering creating my own mix of prosody rate and volume (which do work a little more reliably). This solution seems to work for all voices I test other than Cereproc voices.

Test strings:
```
strong -> Canopy repair <prosody rate="75%" volume="+25%">highly recommended.</prosody>
moderate => Canopy repair <prosody rate="90%" volume="+15%">highly recommended.</prosody>
reduced -> Canopy repair <prosody rate="125%" volume="-15%">highly recommended.</prosody>
```

| Voice | Result |
|---|---|
| Cerevoice Heather | Emphasis has no perceptible effect. |
| IVONA 2 Amy OEM | Emphasis slows and slightly increases the volume of the speech. |
| Microsoft David Desktop | Emphasis slows and slightly increases the volume of the speech. |
| Microsoft Hazel Desktop | Emphasis slows and slightly increases the volume of the speech. |
| Microsoft Zira Desktop | Emphasis slows and slightly increases the volume of the speech. |

**Comment by Tkael** [comment]
I'm going to go ahead and drop in the changes I was mulling over above. I'm not sure whether it'll make an impact with your voice (HARPO Petra 22kHz) but it's worth a shot.
