### ISSUE TITLE
EDDI not remembering EDSM API key (config reset after restarting, intermittent)

### ISSUE THREAD

**Issue by sosborn4** [EDCD/EDDI#1969]
## EDDI version in which issue is found
[Please give the full version number here, not just "latest" or "current"]
3.7.0
## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]
v1.8.6 (not running as plugin)
## Steps to reproduce
1. Start EDDI
2. Click on EDSM Responder tab, provide an API key for EDSM and click button; receive "Obtained log".
3. Close EDDI, restart computer
4. Restart EDDI and click on EDSM Responder tab

## Expected
[Describe what you expected to happen]
Expected EDSM API key to be retained

## Observed
[Describe what happened instead]
EDSM API is missing and has to be reentered.

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
This sounds like a folder permission issue. To test:
1. Start EDDI
2. Click on EDSM Responder tab, provide an API key for EDSM 
  3. Open %appdata%/EDDI/edsm.json in a text editor
  4. If the file is not present or your API key is not recorded, there may be a file permission issue preventing the configuration file from being recorded. 
  5. If the API key is being recorded correctly in the config file, enable verbose logging, restart EDDI, wait 30-60 seconds and check that the API key is missing again, send us the verbose log (which will be eddi.log from the same %appdata%/EDDI on your PC), and disable verbose logging when you are done.

**Comment by sosborn4** [comment]
Hi,

After turning on verbose logging and retesting, I can't now get this to 
happen.  Its no longer happening with verbose turned off either.

However initially, before restarting EDDI, I found that file edsm.json 
was present, but the key was not recorded in there, even though the key 
was showing up in the EDDI UI (I had not restarted EDDI since last 
putting the key in manually).   I'd made no manual changes to the file 
permissions.

Anyway I can't reproduce it now, so I guess close this ticked and I'll 
open a new one with the verbose logs should it start happening again.

Thanks,
Steve.


------ Original Message ------

**Comment by Tkael** [comment]
Now that sounds like an issue obtaining the file contents rather than with saving them. There might be a loading issue that we can improve on. Please keep the ticket open while we look into that.

**Comment by SAMeuse** [comment]
I've been using EDDI 3.7.0 and EDSM for about 2 weeks, and I've experienced this problem.  EDSM *seemed* to work once, perhaps when I initially added the EDSM API to EDDI.  Since then nothing, so I've been importing the journals instead.

I looked at the edsm.json file in %appdata%\EDDI\.  It was created 10/9, and modified today when I re-entered the API.  The contents of the file look correct.  Even though I said I thought EDDI logged to EDSM when I first set up the API key, the "lastSync" field is "0001-01-01T00:00:00".  Perhaps I was wrong.  I do see in the most recent eddiX.log file, "[Warning] StarMapService:SetEd%USERNAME%Credentials EDSM Responder not configured: API key not set."

I followed the instructions you gave above, turning on verbose logging, quitting EDDI, waiting 60 seconds, and re-starting EDDI.  My results were the same as the other Steve--the API and my commander name did persist in EDDI, and the verbose log showed a successful connection to EDSM.

I've attached two logs in a zip file: the verbose log, and the immediately previous non-verbose log showing failure.

Good luck with the triage!

Steve M

[eddi.zip](https://github.com/EDCD/EDDI/files/5440516/eddi.zip)

**Comment by Tkael** [comment]
Thanks for the feedback. The most likely scenario is that EDDI failed to read the file and instead regenerated it (which it is designed to do if it fails ten times in a row to read the file). 

EDDI keeps logs going back 10 sessions. The best information to help us triage the issue would be a log file recording those initial failures to read the file. If that occurred within any of the sessions recorded in your logs then that would be the log that would be most beneficial to us.

**Comment by SAMeuse** [comment]
Unfortunately. My logs don’t go that far back. Sorry I can’t help.

**Comment by Tkael** [comment]
Closed due to inability to replicate. Sorry we couldn't be more helpful on this one. o7
