### ISSUE TITLE
Linux build/support using .NET Core/Wine

### ISSUE THREAD

**Issue by Kreastr** [EDCD/EDDI#1976]
It would be very great if you could make builds of EDDI, that either build natively for Linux using .Net Core or at least test your latest builds using wine/proton with .Net 4.8 installed using winetricks/protontricks and hack around bugs, that are caused by wine WINAPI implementations. Please let me know if you need a tester to report bugs that prevent EDDI from functioning in wine.

**Comment by Tkael** [comment]
Thanks for the feedback, @Kreastr. Elite Dangerous isn't officially supported in Linux so there's been no pressing need or demand to migrate EDDI to .NET core. I imagine that we'll need to migrate eventually as .NET Framework is phased out but we don't have any near-term plans to devote resources to a migration at this time.

**Comment by kolAflash** [comment]
@Tkael  
There's +1 demand from me 😀  
_Debian 12 GNU/Linux, Wine-9.0-rc4_  
Anyway, thanks for the great work on EDDI, which you're probably doing in your free time!

@Kreastr  
Workaround:
Install `dotnet472` and `dxvk` via [Winetricks](https://github.com/Winetricks/winetricks/): `winetricks dotnet472 dxvk`  
Alternatively use [Protontricks](https://github.com/Matoking/protontricks) for Proton/Steam.  
See also here: https://bugs.winehq.org/show_bug.cgi?id=56184

P.S.  
Wine AppDB entry: https://appdb.winehq.org/objectManager.php?sClass=version&iId=41879&iTestingId=114538

**Comment by devurandom** [comment]
@kolAflash Were you able to build the project?

I managed to build it by replacing invocations of `xcopy` with `cp`, changing directory separators from `\` to `/` and adding `mkdir -p` to create the target directories.  But the result would not run, because the project uses WPF (`Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies`).

I found https://www.mono-project.com/docs/gui/wpf/ -- the Mono project itself has no intention of creating a WPF implementation, but they offer some alternatives.  There is https://avaloniaui.net/xpf which is supposed to offer binary compatibility, but requires a rather expensive license that has to be acquired per person and app.  https://opensilver.net/ seems not to target only WPF as used in Silverlight.  I played a bit with https://platform.uno/, but I do not understand enough of .NET, Windows and .NET Framework to build the project for .NET Core 8.0 with WPF 4.8 replaced by Uno 5.2, assuming that it would be (mostly) a drop-in replacement.

**Comment by AlphaCraft9658** [comment]
> [@Tkael](https://github.com/Tkael) There's +1 demand from me 😀 _Debian 12 GNU/Linux, Wine-9.0-rc4_ Anyway, thanks for the great work on EDDI, which you're probably doing in your free time!
> 
> [@Kreastr](https://github.com/Kreastr) Workaround: Install `dotnet472` and `dxvk` via [Winetricks](https://github.com/Winetricks/winetricks/): `winetricks dotnet472 dxvk` Alternatively use [Protontricks](https://github.com/Matoking/protontricks) for Proton/Steam. See also here: https://bugs.winehq.org/show_bug.cgi?id=56184
> 
> P.S. Wine AppDB entry: https://appdb.winehq.org/objectManager.php?sClass=version&iId=41879&iTestingId=114538

It appears that this workaround doesn't work anymore. It simply doesn't launch. Neither does it show why it doesn't launch.

**Comment by redmcg** [comment]
I wanted to add a note here that Wine Mono was updated and fixes the problem mentioned in the wine bug above:
https://bugs.winehq.org/show_bug.cgi?id=56184

EDDI now starts up without any workaround with wine 10.17 and later. Proton Experimental also includes the required fix. 

I haven't confirmed any functionality, but I can confirm it starts and displays the GUI.
