### ISSUE TITLE
Feature: Set your carrier as your "home base"

### ISSUE THREAD

**Issue by cde2496** [EDCD/EDDI#1995]
Just a feature request: 

I like the "home system" idea and I have set mine to Shinrarta Dezhra. However I own a carrier now and my home base is now my carrier!

So I am asking a feature to set your home base as your carrier so that you know when you are close to it, like 5 jump left etc...
In short, same feature as the "Home System" but to your carrier as target wherever it is. :D

It doesn't necessary need to be your own carrier of course. You can park at any carrier as your home base.

Another use case (probably too difficult) would be to remind you to come back to the carrier if it got to jump and you are far away. Or warn you soon enough so you can come back on time (base on number of jumps or distance).

**Comment by Tkael** [comment]
1. We can query / track the current location of your personal fleet carrier via the Frontier API endpoint (see #1828, not yet implemented)
2. Tracking other people's fleet carriers is more difficult - the EDSM API we use to source our data does not allow searching for a station without specifying a star system (even though it is possible to do this from the browser). We'll have to think about whether it would be viable to provide an option like this. If it is possible, it is likely that the data will be much less reliable than for your personal carrier. Most player databases purge fleet carrier data that hasn't recently been updated through EDDN so that they don't report stale information.

**Comment by Tkael** [comment]
Pending #1828.

**Comment by Tkael** [comment]
There will be a `carrier` top level object in 4.0.2 and the `Jumped` event will occasionally report distance to your carrier if no home system is set. Tracking other people's fleet carriers is less reliable so I have chosen not to take that approach.
