### ISSUE TITLE
Delivering mission does not store next system name in system clipboard

### ISSUE THREAD

**Issue by ghost** [EDCD/EDDI#2002]
## EDDI version in which issue is found
v3.7.1

## VoiceAttack version in which issue is found (as applicable)
v1.8.7-Steam

## Steps to reproduce
1. When flying with multiple missions the mission monitor correctly updates the list of missions.
2. If you press the "Get Route" button in EDDI the first system name is copied to the clipboard
3. When delivering a mission it triggers the "Mission completed" https://github.com/EDCD/EDDI/wiki/Mission-completed-event
4. Now the next system name on route is spelled out via TTS, but not copied to the clipboard.

## Expected
Expected same behavior as when pressing the the "Next in Route" button in EDDI. So audio feedback about my next waypoint, but the system name is copied to the clipboard, too.
So not need to worry about missing the audio feedback about your next system, it's already in your clipboard ready to be pasted into galaxy map.

**Comment by ghost** [comment]
I think it is this line within the EDDI personality "Mission completed":
`line 82: {set next_system to RouteDetails("update")}`

Maybe check the RouteDetails("update") if this copies the system name into the clipboard as "Next in Route" does.

**Comment by Tkael** [comment]
Looks like setting the clipboard is currently coded into the UI so if you don't go through the UI then it isn't set. 

I think we ought to add a custom function to allow the user to set the clipboard, then modify the `Route details` script to use that custom function. The UI would trigger still a `Route details` event (as it does now) but the event would modify the clipboard rather than just telling you that the user that the clipboard was modified. 

Users would also be free to implement the custom function to set the clipboard in their other scripts.

I have a private branch that makes some significant changes to how we handle navigation. It's not ready for prime time yet, but I'll consider this for that branch.

**Comment by ghost** [comment]
Thanks. Looking forward to the update.

**Comment by Tkael** [comment]
Pending #2025.

**Comment by Tkael** [comment]
Resolved for the next release (by adding a Clipboard() function and using it within the `Route details` script).
