### ISSUE TITLE
Fines not cleared at interstellar factor

### ISSUE THREAD

**Issue by cde2496** [EDCD/EDDI#2073]
## What's Wrong (please be as specific as possible)

I had 1 700 fine at some system HIP 1914 however I cleared it in a nearby system interstellar factor as I was shot on sight at the HIP 1914 system station.
EDDI still report 500 fine when I come back to HIP 1914.

### Expected
EDDI should not report any fine as I cleared it already.
I also see a lot of claim accumulating in crime monitor however I have cleared all.

### Observed
In the Crime Monitor the fine of 500 credit is still there. So I have to clear it manually.

### Steps to reproduce
As described above, get one or two fine and try to clear in another system.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 3.7.2.rc1
  * VoiceAttack Version: 1.8.7
* Localization [if applicable]
  * EDDI's language: "Automatic"
  * Voice: English Ivona Ami

## My Investigation

Not sure since when it started happening as I usually never get fine or crime! :D
I believe is not due to recent EDDI version as I had it too in the past.

**Comment by cde2496** [comment]
![EDDI](https://user-images.githubusercontent.com/5187396/104180062-ae61fa80-5447-11eb-8756-c2a4ec85f814.png)

**Comment by Tkael** [comment]
Were all fines and bounties accumulated during a single play session?
Was EDDI running the entire time?
Can you please share your player journal from the applicable play session?

**Comment by cde2496** [comment]
I it was in a single play I always start Voice Attack while playing.

**Comment by cde2496** [comment]
[Journal.210111201403.01.log](https://github.com/EDCD/EDDI/files/5801880/Journal.210111201403.01.log)
[Journal.210110210602.01.log](https://github.com/EDCD/EDDI/files/5801882/Journal.210110210602.01.log)
[Journal.210110134123.01.log](https://github.com/EDCD/EDDI/files/5801883/Journal.210110134123.01.log)
[Journal.210109232024.01.log](https://github.com/EDCD/EDDI/files/5801884/Journal.210109232024.01.log)

**Comment by cde2496** [comment]
Not sure which one you need so I upload yesterday and sunday.

**Comment by cde2496** [comment]
Its in the last file: 
{ "timestamp":"2021-01-09T19:20:04Z", "event":"PayBounties", "Amount":700, "Faction":"$faction_Empire;", "Faction_Localised":"Empire", "ShipID":7, "BrokerPercentage":25.000000 }

**Comment by Tkael** [comment]
With respect to bounties... there is a bug when claiming multiple bounties from interstellar factors where the faction name isn't written to the player journal.
```
{ "timestamp":"2021-01-11T13:07:44Z", "event":"RedeemVoucher", "Type":"bounty", "Amount":1378949, "Factions":[ { "Faction":"", "Amount":175148 }, { "Faction":"", "Amount":97537 }, { "Faction":"", "Amount":351443 }, { "Faction":"", "Amount":557657 }, { "Faction":"", "Amount":197164 } ], "BrokerPercentage":25.000000 }
```
We try to work around this by trying to match the totals in the crime monitor for each faction against the reported values to try to guess the faction being claimed but this is not a very robust method. There is also no initial event written at the beginning of a play session with pending fines and bounties, leaving any errors to compound from one session to the next. Hooda, the original author of the crime monitor, made sure that the crime monitor would be easily editable exactly because this tracking could be disrupted. 

I examined Journal.210111201403.01.log. In that play session, you earned 1920395 credits in bounties but claimed 7946191 (less brokerage fees). The workaround described above may have failed if bounties carried over from a prior session where EDDI hadn't recorded bounties and thus had an inaccurate total for a faction. Since the faction names aren't evident from the journal event, the only recourse would be for you to manually clear the bounties.

**Comment by Tkael** [comment]
None of the four journals includes a `PayFines` event. 

The event you noted above records that you paid off a bounty assigned against you by the Empire. Not a fine.

**Comment by Tkael** [comment]
Thanks for reporting. After investigating, I believe this is working as intended (within the limitations I noted above for the data we receive about crime and punishment). o7
