### ISSUE TITLE
Incorrect information on arrival after jump

### ISSUE THREAD

**Issue by feczo** [EDCD/EDDI#2102]
[eddi_issue.zip](https://github.com/EDCD/EDDI/files/5899567/eddi_issue.zip)
![20210131215538_1](https://user-images.githubusercontent.com/3347261/106381825-a1fe0b80-640f-11eb-8a5e-987870ab95e4.jpg)
[Journal.210131154557.01.log](https://github.com/EDCD/EDDI/files/5899569/Journal.210131154557.01.log)

"1 jump until arrival.  Information:   Olkolo Energy Partners are in civil war and The 9th Legion are investing in its infrastructure  Warning: TASMAN DEVIL 07 is wanted in this system by 1 faction, for total fines and bounties of 200 credits. There are 8 stations to clear your pending fine. The nearest is Soukup Terminal, 420.4 light-seconds from the main star.
"

Issues:
I) There are no more hops on route, this is the final destination - yet I hear 1 jump until arrival
II) TASMAN DEVIL is not wanted here ... it was cleared a few jumps before with an interstellar factor 

attaching both EDDI log and game journal log

**Comment by Tkael** [comment]
If you have a mission destination set, EDDI may be referencing that as your final destination. You can clear the current route from the Mission monitor if that's the case. 

Crime can become out of sync due to scarce information in the player journal - there is no event to summarize current crime status so we have to hope that EDDI is always running so that we can capture the full record. Even then, we have to make assumptions for some crime events because the game doesn't in every case provide enough information to link records to factions. Because of these shortcomings, it would be a good idea to look at the Crime Monitor and clear any incorrect information from time to time.

**Comment by Tkael** [comment]
Closing as (presumably) resolved. I wish we could do more with the Crime Monitor but we really are constrained by the quality of data we receive from FDev.
