### ISSUE TITLE
ShipName review

### ISSUE THREAD

**Issue by Teun888** [EDCD/EDDI#2124]
## What happens now
The variable Shipname() includes the word "your" when converting to speech. So it will only say "your python is repaired" for example.

## What I'd like to happen 
Remove "your from the standard variable. So it can say "python is repaired".

## How it can happen
See above

## EDDI Version
3.7.2

**Comment by Tkael** [comment]
Do you use a EDDI with a language other than English?

Using a possessive "your" for unnamed ships with ShipName() is intentional. The current version hard codes an English "your" which admittedly isn't well suited for non-English language localization. The next version will allow the possessive "your" to be localized by translators.

If you would like just the model name, consider using `ship.phoneticmodel` or `ship.model` rather than `Shipname()`?

**Comment by Tkael** [comment]
This change was incorporated for the next release by https://github.com/EDCD/EDDI/pull/2105.
