### ISSUE TITLE
Pilots spoken name wrong pronounced

### ISSUE THREAD

**Issue by feiercrack** [EDCD/EDDI#2140]
hi,

 i had never any issues with that, but in current version, where i can hear my CMDR name under --> commander details --> name spoken --> Hear it

its totally wrong pronounced.
what to do?
i already did an new windows 10 speech recognition training

my name is feiercrack, it should be pronounced as the english word for FIRE, like Fire-crack, but now its pronounced like Favor-crack
with same Zira voice selected. i did not made any changes in my audio settings!

**Comment by Tkael** [comment]
1. What is the IPA that you are using to represent your commander's name? Are you using Microsoft Zira, or are you using another voice and also testing with Microsoft Zira? I'm not certain from your description. Please provide as much detail as possible to help us to replicate the issue you are describing.
2. We use a template to prompt you to provide specific information when you open a ticket so that we'll have the tools we need to help you. Because the template wasn't followed, we're missing important context and details that we would need to provide an effective response. Please resubmit a new ticket following the template.

**Comment by feiercrack** [comment]
thanks for response!
1. What is an "IPA" ?
2.  Where to find that "template" u talking about?
3.  As is wrote above, i had selected Zira!
4. Thanks

**Comment by Tkael** [comment]
1. If you'd like to customize the pronunciation of your commander's name, you would do so using the International Phonetic Alphabet (IPA). Click the links in the UI at the top of the `Commander Details` tab for more information.
![image](https://user-images.githubusercontent.com/4382539/111562892-33250980-8754-11eb-982c-787209eea860.png)
2. [Here](https://github.com/EDCD/EDDI/issues/new/choose)
![image](https://user-images.githubusercontent.com/4382539/111563019-69fb1f80-8754-11eb-96cd-9137a862e243.png)
3. Thanks for clarifying
4. Your welcome

**Comment by Tkael** [comment]
May I suggest `ˈfaɪɚkɹæk` for the spoken version of your name using IPA?
