### ISSUE TITLE
Check if a Codex item is nearby

### ISSUE THREAD

**Issue by UseLessUK** [EDCD/EDDI#2148]
It would be a nice feature if EDDI could be setup to check if a codex entry is within a selected Ly range of say;

500, 1000, 1500, 2000, 2500

you could even go to a user defined max say 5000 Ly.

Then if you're out exploring and a codex entries reported location is within the specified range you'd be notified and can then choose to visit it or not.

**Comment by Tkael** [comment]
I'm not sure that this possible with the resources currently available. I'm not aware of any API that shares codex entry data. Codex entries are not transmitted via EDDN.

**Comment by UseLessUK** [comment]
Yeah wasn't sure myself, hence the putting it out there ... but it would be a lovely feature to have in EDDI.

I've just been up to the Conflux Alpha/Beta/Delta/Gamma sites and after getting back to the bubble checked on some codex entries, which if I'd checked while in the area I was in I could have detoured a couple of time to complete some codex items.

**Comment by Tkael** [comment]
Closing as probably not currently viable. We'd either need an API that could return nearby POI from your location or a readily accessible list of POI with coordinates for each (ideally something similar to #1714). Neither seems to be readily available at this time. 

The Canonn API is the closest to making this viable but there isn't a good way to query it efficiently for location specific data. Essentially, we'd need obtain a dump of the Canonn data so that we could search by coordinates for nearby POI. 

We would likely also want to track your current codex status for each region (so that we don't recommend POIs similar to those you've already visited). The journal data we have currently could suffice for this purpose, but not without reading back through many prior journal logs (hoping that you have a complete record from prior play sessions). There is no journal event summarizing codex completion status when you start a game.
