### ISSUE TITLE
General Volume slider for sounds, and a Volume optional parameter in Play() function

### ISSUE THREAD

**Issue by parduz** [EDCD/EDDI#2156]
## What happens now
You may play a sound using "Play()", but there's no control on the volume of the sound, so it may be too low or too high relative to the used Voice volume.

## What I'd like to happen 
I would like to have a "global Sounds volume slider" like the one already there for the Voice, and a "Volume %" optional parameter for the Play() function to "fine tune" a single sound volume.

_(With "Volume" i mean "the loudness". I'm not sure what's the best term)._

## EDDI Version
3.7.3

**Comment by Tkael** [comment]
Hmm, since the `Play()` function is linked to the speech synthesizer it should currently be using the same volume setting as speech. 

We'd need to either override the speech volume temporarily or break the connection to the speech synthesizer and play sounds entirely outside of that context. 

We'd also need a public domain sample sound file that we can use for testing volume.

**Comment by parduz** [comment]
> Hmm, since the `Play()` function is linked to the speech synthesizer it should currently be using the same volume setting as speech.

Yes, but the "recorded" volume of the voice and the sounds may be really different.

> We'd also need a public domain sample sound file that we can use for testing volume.

https://notificationsounds.com/
