### ISSUE TITLE
Crime Monitor - pending faction fines should be converted to bounties when a bounty is issued

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#2185]
## What's Wrong (please be as specific as possible)
In game, any pending fines are converted to bounties when a commander is assigned a bounty. EDDI's Crime Monitor does not mirror this behavior, resulting in less accurate fine and bounty reporting.

### Expected
Pending fines are converted to bounties when a bounty is assigned to the commander, matching game behavior. 

### Observed
Pending fines are not converted to bounties when a bounty is assigned to the commander. 

### Steps to reproduce
1. Be assigned fines by a faction.
2. Be assigned bounties by a faction.
3. Review the in-game Transactions tab. Note that fines have been converted and added to the bounty. 
4. Review EDDI's Crime Monitor. Note that fines and bounties continue to be reported as separate totals.

### Configuration
* Version 
  * EDDI Version: 4.0.0-b3
  * VoiceAttack Version: N/A

**Comment by Darkcyde13** [comment]
I noticed this too, last thing last night, after I reported the Crime report script error.

I also found out that handing yourself in won't clear the crime monitor, because the event has practically no information.
`{ "timestamp":"2021-05-28T23:55:59Z", "event":"Resurrect", "Option":"handin", "Cost":0, "Bankrupt":false }`
I'm wondering if this is a bug?  Should the 'cost' be filled with the amount of your bounty?  I did see that even in game, cost was zero, so I'm not sure if it should or not.  There isn't anything else in the Journal to say that you've paid off your bounty.

The only thing I can think of (assuming the Journal entry is all correct) is to use the stations controlling faction to clear all bounties assigned to them from the crime monitor (when you hand yourself in anyway).  Otherwise, we'll have to manually remove them all the time.  However, I'm not sure how well that would work, although I did have to fly to a station controlled by the faction I owed, before I could pay anything.  Even Interstellar Factors wouldn't let me pay my bounty off, which leads me to think that's another bug in the game.

**Comment by Tkael** [comment]
Another observation: When paying off a bounty at interstellar factors I'm seeing a `PayFines` event, rather than a `PayBounties` event, logged in the player journal. The last time I've seen `PayBounties` in the player journal was Feb. 28 2021.

**Comment by Tkael** [comment]
Resolved by https://github.com/EDCD/EDDI/commit/bdccb93f467e7d3a2dfaa4eaa1e46b14ec042da4
