### ISSUE TITLE
RouteDetails("route") does not set a route destination

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2232]
### Expected
RouteDetails("route") to populate 'destinationsystem.name' with the first system, and 'destinationdistance' to have the correct distance.

### Observed
After RouteDetails("route") is invoked, 'destinationsystem.name' is blank, and 'destinationdistance' is zero.  'destinationsystem' is 'void'.

### Steps to reproduce
1. Take some missions.
2. Run RouteDetails("route")
3. Check the 'destinationsystem.name' and 'destinationdistance' variables.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v4.0.1-b1
  * VoiceAttack Version: [if applicable] 
* Localization [if applicable]
  * EDDI's language: English
  * Voice: Ivona Amy

### Investigation Notes
Copied from my forum post:

==================
OK, so I've tried this out now. I will admit, I'm not 100% sure I'm doing this right, but this is what I've done:

I've taken a few quick delivery missions to nearby systems, and then run RouteDetails("route"), with this output:
"Missions route calculated for 3 systems. Total route distance is 48.0 lightyears. First mission destination is C D-51 1 4 4 7, 15.6 lightyears away."

I've then selected the system in the galaxy map (and set a route to it), and tested the variables destinationsystem.name & destinationdistance. destinationsystem.name is blank (and destinationsystem is 'void'), and destinationdistance is zero.

I then went and completed the first delivery mission, and got this:
"Next mission destination is Esubilanque, 12.9 lightyears away."

Now I get destinationsystem.name and destinationdistance filled with the correct information, as per the output above. Jumping to Esubilanque, I now get it telling me I have arrived: "... Silcarius has arrived at the Esubilanque system.... "

So, as long as I'm doing this right, it looks like these variables are only being populated when a RouteDetails("update") is performed (and successfully completed), but not when a RouteDetails("route") is done to begin with. This means that if you only have one mission, it will never tell you that you have arrived at your mission destination. If you have 2 or more, then it will tell you for the second one and each after that.

===================

Just a quick FYI:  I tested destinationsystem using dump(), that's how I found it was 'void'.  I wasn't sure if that would be relevant or not.

### EDDI Logs
None

### Player journals
None

**Comment by Tkael** [comment]
The proper flow, as currently programmed, appears to be:
1. `{RouteDetails("route")}` 'Traveling Salesman' (RNNA) route for all active missions. Takes a system name as an optional secondary argument. If set, the resulting route shall be plotted relative to the specified star system rather than relative to the current star system. This *proposes* a route but does not set it (see step 2).
2. `{RouteDetails("set")}` Set destination route to a single system. Sets the route destination to the last star system name returned from a Route details event. An optional second argument sets the route destination to the star system name specified instead. An optional third argument sets the destination station. This sets the actual destination.
3. (Do mission stuff)
4. `{RouteDetails("update")}` Update to the next mission route destination, once all missions in current system are completed. Takes a system name as an optional secondary argument. If set, the resulting route shall be plotted relative to the specified star system rather than relative to the current star system. This updates the mission destination.

**Comment by Tkael** [comment]
Eliminating "set" could help make this simpler (so that two calls to RouteDetails() in the same script are much less likely), but that could also significantly change the experience for users using the current setup, particularly in VA. Additional community feedback on this point would be most welcome.

**Comment by Tkael** [comment]
Note that both "route" and "set" already have optional secondary arguments.

**Comment by Tkael** [comment]
Resolved for next update by changes to the `RouteDetails()` function and navigation service.
