### ISSUE TITLE
Current System Variable not set in VoiceAttack

### ISSUE THREAD

**Issue by Vlodec** [EDCD/EDDI#2261]
Further to our short discussion on Frontier forum regarding an issue with EDDI variables:

Windows 10 Home 64-bit
AMD Ryzen 9
Gigabyte Technology X570 Aorus Master (AM4)
Nvidia GeForce GTX 1080 

The system variable {INT:System total bodies} gives a retrurn of either 1 or 0, except on startup, when it gives the correct number. A jump to another system will always corrupt it.

{INT:System scanned bodies}, and {INT:System mapped bodies] only ever give a return of zero, again, except on startup when the number is correct.

~~The variable {DEC:Status fuel percent} sometimes is correct on startup, in which case it remains correct, or it returns "not set", in which it continues to return this message,~~ (resolved in a separate ticket)

It wasn't always so: I have no idea what's causing it. Tried re-installing EDDI - made no difference. Latest version of ED  Odyssey made no difference. Nvidia driver upadate made no difference. I'm not aware of any other changes.

### Expected
Clearly I expect EDDI to return the correct numbers.

### Observed
I have various VA commands which use these variables. A commonly used one is "Say, '{INT:System total bodies} discoverable bodies. {INT:System scanned bodies} bodies scanned. {INT:System mapped bodies} bodies mapped.'"

### Steps to reproduce
Use command above 

### Configuration
  * EDDI Version: 4.0.1
  * VoiceAttack Version: 1.8.9 64-bit

### EDDI Logs
[Any log files providing additional details about what happened. These are located at %APPDATA%/EDDI and have the extension ".log"]

Log files (verbose) appended as requested
[reddit.log](https://github.com/EDCD/EDDI/files/7218385/reddit.log)
.

**Comment by Tkael** [comment]
Yep, something seems to be off. I suspect that VoiceAttack is being updated when the star system object changes but not when properties of the star system object change. Because of that, you'll actually have more complete information if you jump out of a system and then jump back in. I'll investigate.

**Comment by TerribleTony** [comment]
I'm having this exact problem after downloading voice attack through steam and setting up the EDDI plugin about a week ago. I see that issue is closed, I'm wondering if there has been a reversion since then or if I dont have the correct version installed now. This is the only thread online I can find that discusses this problem. Any advice welcome. 
to be specific  {INT:System total bodies} and {INT:System scanned bodies} are always 0 after a d-scan. {INT:System scanned bodies} did once return a value (this is was 12 or something) after I loaded into a previously scanned system and performed a d-scan again.
