### ISSUE TITLE
Eddi not registering multi-function limpet controllers

### ISSUE THREAD

**Issue by EmporiaHall** [EDCD/EDDI#2317]
nor is it detecting the weapons on guardian fighters

**Comment by Tkael** [comment]
Multi function limpets controllers will be added in the next update.

Guardian fighter loadouts should be supported now. Please provide more details about the specific Guardian fighter that is not being parsed correctly. Please also provide a debug log where you trigger the fighter logout description with the Frontier API enabled so that we can review the data being reported to EDDI.

o7
