### ISSUE TITLE
Small '.shortname' bug for body names

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2345]
### Expected
.shortname to give a suitable short name for a body.

### Observed
.shortname seems to simply strip out the system name from a full body name.  This is incorrect for certain bodies, like "Planet Lave", which becomes just "Planet", resulting in descriptions such as "Planet Planet" in scripts that use '{reportbody.bodytype} {reportbody.shortname}'.

### Steps to reproduce
1. Find a body where the system name is part of the body name, but not the first part.  i.e. "Planet Lave" in the Lave system.
2. Test '.shortname'
3. Observe it is simply "Planet"

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version:  v4.0.1
  * VoiceAttack Version: N/A
* Localization [if applicable]
  * EDDI's language: British English
  * Voice: Ivona Amy

### Investigation Notes
I came up against this today when travelling through Lave.  After checking what was causing EDDI to say "Planet Planet" I found that .shortname is simply stripping the system name from the body name.  Now in 99.99% of cases, this will be fine, but in this case (and possibly others) it's totally wrong.

As a quick temporary workaround, I've made a check for the system name, and only use .shortname if the system is part of the body full name, and starts at position zero in the string.  Like this:
```
    {_ Check if system name is at the beginning of the body name _}
    {if find(body.name, reportSystem.name) = 0:
        {set shortname to body.shortname}
    |else:
        {set shortname to body.name}
    }
```
I guess it should also check for the body type at the beginning of the string too, to avoid instances like "Planet Planet Lave".

I think the logic that creates .shortname just needs a little updating to account for edge cases like this.

### EDDI Logs
N/A

### Player journals
N/A

**Comment by Tkael** [comment]
Huh, nice catch. It should be an easy fix to adjust that algorithm.

As far as the use of 'Planet' within the proper name, it looks like there's a few of these but the others follow a different pattern. 
![image](https://user-images.githubusercontent.com/4382539/174468483-e47464b5-b557-47b7-a7c0-b84e68e11b75.png)
![image](https://user-images.githubusercontent.com/4382539/174468745-9352704c-d957-4b40-80cd-ba346fe78a67.png)
It's probably appropriate to keep the proper name as-is rather than stripping the planet type portion of the proper name. Otherwise, Earth's moon would have an empty string for a name and we'd some some other odd namings. ;-)

**Comment by Darkcyde13** [comment]
> Otherwise, Earth's moon would have an empty string for a name and we'd some some other odd namings. ;-)

Yeah, that had occurred to me too, but I wasn't sure if it was 'Moon' or 'Luna', and I didn't think to check before I went to bed last night.

As for the body type being removed too, I was only thinking if it was at the start of the name, and in your examples, that only applies to 'Planet Lave'.  Having something like "Planet Thompson's Planet" (bodytype + bodyname) is perfectly fine, and if Lave is the only one where it's at the start, then I see no problems just leaving things as they are in that respect.

**Comment by Tkael** [comment]
I'm happy to correct the issue so that `Planet Lave` is rendered as `Planet Lave` but I do not wish to meddle further - the variable should return the full proper name for the body even if that proper name contains a body type. 

If you need to strip the body type from the proper name to improve the flow of your script then you already have the tools to do that at the script level. Sorry and I hope you understand. o7
