### ISSUE TITLE
{DEC:System distance from home} does not work

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#2404]
{DEC:System distance from home} does not work, EDDI API speaks it correct, but the variable does not calculate

### Expected
Should give the correct distance in LY decimals with ((EDDI:Jumped)) command

### Observed
Does not calculate, gives error

### Steps to reproduce
Every time I jump

### Configuration
Horizons 4.0
  * EDDI Version: 4.0.1
  * VoiceAttack Version: 1.10.3
* Localization ??
  * EDDI's language: English
  * Voice: Microsoft Zira

[eddi.log](https://github.com/EDCD/EDDI/files/9747101/eddi.log)

**Comment by nepomuk16321** [comment]
Hello FireSammy, I am wondering about the supposed error. On the EDDI page "Jumped-event" I do not find the variable you mention. https://github.com/EDCD/EDDI/wiki/Jumped-event If this variable is not generated by EDDI for Voice Attack (or you generate the variable), then Voice Attack cannot use it. A question about the announced distance. Does the announcement come over Voice Attack or from EDDI directly ? That the announcement comes from EDDI is possible, because EDDI generates own variables and uses them for the announcement (here: system.distancefromhome).

**Comment by Tkael** [comment]
There are unfortunately some known issues with selective variable updating in our top level objects in 4.0.1. I believe these should be fixed in the next release.

**Comment by Darkcyde13** [comment]
> Hello FireSammy, I am wondering about the supposed error. On the EDDI page "Jumped-event" I do not find the variable you mention. https://github.com/EDCD/EDDI/wiki/Jumped-event If this variable is not generated by EDDI for Voice Attack (or you generate the variable), then Voice Attack cannot use it. A question about the announced distance. Does the announcement come over Voice Attack or from EDDI directly ? That the announcement comes from EDDI is possible, because EDDI generates own variables and uses them for the announcement (here: system.distancefromhome).

This is a variable that should be available for Voice Attack, as mentioned here in the VA help: https://github.com/EDCD/EDDI/wiki/VoiceAttack-Integration#current-system-variables

**Comment by nepomuk16321** [comment]
Ohhh, I hadn't looked in that section (scroll down page). OK, all clear. That was my mistake then.
Thanks @Darkcyde for the correction.
But with that we have uncovered another small problem, the help pages are not ... ähh how do you call that ... stringent, logically coordinated. But this correction is not so important for now. A new version of EDDI is much more important.

**Comment by Tkael** [comment]
This should be fixed in 4.0.2 (currently in beta testing).
