### ISSUE TITLE
EDDI does not speak in configured language

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#2407]
### Discussed in https://github.com/EDCD/EDDI/discussions/2406

<div type='discussions-op-text'>

<sup>Originally posted by **tbayart** October 14, 2022</sup>
Hi here,

I'm french on a french Windows 10 but i'm running all my programs in english, including Elite Dangerous.
EDDI is setup for english and all texts are displayed in english.
In Speech Responder, i checked a few scripts and most of them are in english.

I enabled speechresponder.out
it contains french phrases but the speech is english so it's really really weird

I want to get english phrases for proper english voice
What am i doing wrong ?</div>

**Comment by Tkael** [comment]
From what has been said in the discussion so far, at least part of this issue may have to do with threads triggered from VoiceAttack plugin contexts. Since these threads are created by VoiceAttack in response to a plugin command, they would inherit the VoiceAttack / system default thread culture. We can override / set that back to your selected culture.

You reported that the event scripts are being read out in French and you say that the UI is displaying in English. If this is occurring then that might indicate a need to manually override the thread cultures for additional application threads (it is difficult to replicate and test for this on my computer). 

Are both of these observations (scripts being read out in French and the UI displaying in English) happening in the same application instance (with EDDI running as a plugin in VoiceAttack)? Or are you looking at the UI in standalone in English, closing standalone, starting VoiceAttack, and then hearing French events? 

If you use the `configuration` [EDDI plugin context](https://github.com/EDCD/EDDI/wiki/VoiceAttack-Integration#configuration) to display EDDI's window while VoiceAttack is running, is the UI displayed in English or French?

It may be helpful for me if you could record a short video, upload it to Youtube, and post a link here to show me exactly what you are observing.

**Comment by Tkael** [comment]
Aha! I think I may have found something specifically related to fetching the correct culture-specific scripts file. Full investigation will need to wait, it's very late here and i need to 💤 . If I'm right though then the UI will be in English but the scripts will all be French (but only when the UI is opened from VoiceAttack as described above).

**Comment by Tkael** [comment]
Ok, I think I understand the issue (UI being loaded before the language setting was fully applied) and I think I have a fix. I'm working towards a new beta release and when that is released I'd appreciate it if you would re-test this and let me know if there is still an issue.

**Comment by tbayart** [comment]
Hi, i retrieved the source and built it.
Then i ran EDDI as a VA plugin.

Here is the `speechresponder.out` from commit 6f2771b7dac15d58e74429ec8ff849becb7fc586 at startup :
> vous permet daccéder aux améliorations de grade.
Plus que 97 pourcent pour passer au rang suivant en combat. Plus que 87 pourcent pour passer au rang suivant dans le commerce. Plus que 76 pourcent pour passer au rang suivant en exploration. Plus que 97 pourcent pour passer au rang suivant pour le championnat cékucé. Plus que 27 pourcent pour passer au rang suivant dans l'empire. Plus que 33 pourcent pour passer au rang suivant dans la fédération.
Bienvenue commandeur.
Vous êtes Parké dans la station orbitale Robigo Mines, dans le système Robigo.
vous n'avez aucune mission.

Here is the startup output since your commit cf0896540fabcbbc1e2fe5ab4c0c5edc50edc7e2 :
> Welcome back commander.
You are docked at Outpost, Robigo Mines, in the Robigo system. You are allied with the local faction, Sirius Corporation.  Information:  Robigo Cartel are ahead in a Civil War with CdE Corporation for control of Cukkemane's Nest.  Sirius Corporation are enjoying an economic boom
You have no missions at this time.

Your commit solved the issue.

BTW i tested changing the language in EDDI and after a restart the output matches the selected language.

**Comment by Tkael** [comment]
Awesome. Thanks for taking the time to report back. o7
