### ISSUE TITLE
Error in "Undocked" script

### ISSUE THREAD

**Issue by Sharparam** [EDCD/EDDI#2426]
When undocking, the TTS says

"Error with undocked script: Object reference not set to an instance of an object"

The issue goes away if the last line in the script is commented, `{set next_system to RouteDetails("update")}`, but whatever functionality that line is meant to give is then not available I'd assume.

Playing Horizons (4.0)
EDDI version: 4.0.2-b1
Running as VoiceAttack plugin, VA version: v1.10.3
It also runs the EDDI profile as a linked profile from HCS' profile (HCS plugin version v3.8.4)

**Comment by Tkael** [comment]
The line you highlighted would update trigger a guidance update if you had previously plotted a ship route in the Navigation Monitor and enabled guidance, otherwise it should be inert.

Would you please attach the eddi.log file from that play session for review? It may provide more detail about the specific object that triggered the problem. Likewise, a copy of `navigationmonitor.json` may be helpful. Both files are found in the `%appdata%/EDDI` configuration file location on your system.

I'll go ahead and add some speculative null protection to the method but the information that you provide will help check that I'm addressing the correct code to prevent the issue in future.

**Comment by Sharparam** [comment]
Meanwhile, I've discovered that a similar error happens in the "Jumped" script, after completing a jump to a system, with the same null reference error. That script is quite a bit larger though so unsure which line it's happening on so far.

Here's the log files (restarted VoiceAttack a few times so it's been split), where both the original issue and the one from the "Jumped" script should be logged.

[eddi.log](https://github.com/EDCD/EDDI/files/10108158/eddi.log)
[eddi1.log](https://github.com/EDCD/EDDI/files/10108159/eddi1.log)
[eddi2.log](https://github.com/EDCD/EDDI/files/10108160/eddi2.log)

And the `navigationmonitor.json`:

[navigationmonitor.json.txt](https://github.com/EDCD/EDDI/files/10108167/navigationmonitor.json.txt)
(GitHub interestingly does not allow JSON file uploads in issue comments so I had to add `.txt` to it)

At the time of uploading those files, I currently am in the Deciat system with Deciat 6 A targeted.

Edit: Oh, of course, the "Jumped" script also has the line `{set next_system to RouteDetails("update")}` near the top so it's likely the same issue.

**Comment by Tkael** [comment]
Thank you. Unfortunately, the standard logs didn't provide enough detail to allow me to be sure that my changes will correct this issue. Would it be possible to temporarily enable verbose logging, trigger the exception one more time, and then zip and attach the resulting verbose log to this ticket? o7

**Comment by Tkael** [comment]
Presumed fixed by 19d730a50cd06b24e83e6ed6abddfa78b06fecfa.
