### ISSUE TITLE
EDDI Not Sending Data to INARA or EDSM

### ISSUE THREAD

**Issue by kc9eye** [EDCD/EDDI#2435]
INARA data was visibly not being updated when traversing the galaxy or inventory updates. Also, EDSM data was not updating on their site while traversing the galaxy. There is no real immediate way to say the same for EDDN. 

Expected data on both INARA and EDSM to display updates over an appropriate time frame. However, no updates were observed.

Looking at the logs, there appears to be some journal things that are unknown in EDDI, along with error to both the INARA and EDSM API's

### Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 
  * VoiceAttack Version: [if applicable] 
* Localization [if applicable]
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"]
  * Voice: [Name and language]

### Investigation Notes
[Any investigation you have done, tests using default scripts and personalities, regression tests against earlier versions, etc]

### EDDI Logs
[Any log files providing additional details about what happened. These are located at %APPDATA%/EDDI and have the extension ".log"]

### Player journals
[These are not required if EDDI Logs are verbose but may be helpful otherwise. They are located at [your Saved Games folder]/Frontier Developments/Elite Dangerous/. Please only provide excerpts or attach files from the play session where the issue occurred.]
[eddi3.log](https://github.com/EDCD/EDDI/files/10199512/eddi3.log)

**Comment by Tkael** [comment]
`2022-12-08T20:53:44 [Info] EDDI:.ctor EDDI 4.0.1 starting`
You are running EDDI version 4.0.1. After the Elite galaxy split (e.g. "LIVE" or 4.0 vs. "LEGACY" or 3.8), EDSM and Inara announced that they would no longer accept data from the LEGACY galaxy. Since EDDI was not previously required to send data about the active game version or to block data from Elite version 3.8, EDSM and Inara now refuse data EDDI version 4.0.1. This is the expected behavior and can be corrected by updating EDDI to the latest beta release.

EDDI version 4.0.2-b2 (which supports the updated sending requirements set by Inara and EDSM) is now available.  The release notes are [here](https://github.com/EDCD/EDDI/releases/tag/Release%2F4.0.2-b2) and a link to the installer is available [here](https://github.com/EDCD/EDDI/releases/download/Release%2F4.0.2-b2/EDDI-4.0.2-b2.exe).
