### ISSUE TITLE
Different lines not joining in the same sentence [Cottle parser broken?]

### ISSUE THREAD

**Issue by Transcan** [EDCD/EDDI#2511]
## What's Wrong
I am having problems with several scripts that are not doing the line joining correctly (look at the example below for better understanding about what I'm saying).
Phrases that should be joined in a single sentence fails to do so and are splitted in several lines, so they are read with unwanted pauses.
Some scripts works, some don't.
I have tested the same script with the default English personality and it works as expected. But my script is just a literal translation from English and it fails.
In fact, I have copied the English script and pasted it in front of my code, and it fails just like mine.
After some investigation, I found out it has nothing to do with a syntax error, but to something I don't know.

### Steps to reproduce
I managed to easily reproduce the error like this:
- Configure EDDI into Spanish.
- Clone the default personality.
- Edit the "**Died**" script
- Delete the content and replace it with this example:
```
{if true:
    Your Ship
    has been
} destroyed
.
```
- Press the test button and check _speechresponder.out_ file.

### Observed
The result is spoken with a pause and if you look the file it shows like this:
```
your ship has been
  destroyed
.
```
Notice that the two lines inside the **_if_** are indeed joined (as expected), but not the rest.

### Expected
The expected result is the phrase spoken in one line (without pauses) and looks like this in the file:
```
Your Ship has been destroyed.
```

### Investigation Notes
Now the weird part:
Do the same, but this time with "**Crime report**" script instead of "**Died**".
You will see that this time, the result is as expected. Same code, different result. The only change is the script that holds the code.
Maybe it has something to do with the default parameters given to the script for the test button to work (you know, those to fabricate an example event), but it seems it doesn't affect when EDDI is in English... I don't know.

### Configuration
* Version
  * EDDI Version: v4.0.2 (never noticed this behaviour in previous versions)
* Localization
  * EDDI's language: [Spanish] Not tested with others.
  * Voice: [Spanish] but I guess it doesn't matter.

**Comment by Transcan** [comment]
Maybe it has something to do with this?
https://cottle.readthedocs.io/en/stable/page/04-configuration.html#trimnothing
Its the same behaviour (but doesn't explain why the plain text inside the {if} works...)

**Comment by Tkael** [comment]
The voice might actually matter here more than you think. The voice is more than a voice - it is software that interprets written text and determines how it should be spoken. Line breaks, pauses, speech cadence, etc. will not be handled equally by all voices. Further, voices are usually targeted towards specific languages and may not support any secondary languages as completely or as gracefully. Whatever the result, however, it should be consistent across events. If it's not then perhaps some white space characters in one script or the other is changing the way that the text is interpreted and rendered by the voice?

That said, I'm not seeing the same behavior with respect to the output from speechresponder.out on my nightly build (possibly as a side effect of some other changes I've made under the hood to clean up extraneous white space characters).  Using the same script you provided, I'm currently yielding `Your Ship has been destroyed.` (same as your expected result) from speechresponder.out. Consequently, if the voice is rendering differently due to white space characters I think the next release should yield more consistent results.
