### ISSUE TITLE
Always announces all mappable planets scanned

### ISSUE THREAD

**Issue by Ricochetv1** [EDCD/EDDI#2576]
When doing surface mapping of planets, after every planet, it announces that all worthwhile planets have been mapped, even if that is not the case. It would be much more useful for it to say which other planets are worthy, and it would be nice to be able to set a threshhold in the options for what it considers worthwhile.

**Comment by Darkcyde13** [comment]
Are you using a modified version of the 'Bodies to map' script?  Because the default should already do what you are asking.

There is a setting at the top of the script for a minimum value threshold `highValueThreshold` where any body exceeding this value will be reported.

The script also filters bodies that you have already mapped, and so should not report them once you have mapped them, even if they exceed the set threshold value.

**Comment by Ricochetv1** [comment]
I haven't modified anything. I'll check out the script for that threshold.

**Comment by Tkael** [comment]
There's also the question of whether you want bodies in fully explored and populated systems to be reported (which is another preference).
Closing as presumed resolved for the time being.
