### ISSUE TITLE
EDDI crashes to desktop whe pressing "login" on the frontier API page

### ISSUE THREAD

**Issue by shodanx2** [EDCD/EDDI#2579]
EDDI crashes to desktop when pressing "login" on the frontier API page

It crashed, tried again, crash again

Tried logging in to fdev in my browser, still crash

Here is what it shows before crash to desktoping

https://i.imgur.com/vgqFA9z.png

(I could not paste the image directly here)

**Comment by Tkael** [comment]
Unfortunately, there isn't enough information in this ticket for me to offer any help.

Please create a new ticket following the template we've created so that we have some basic information about the circumstances surrounding this crash. In particular, please include at least one of your .log files from a session where this crash has occurred. A verbose .log would be best (please turn verbose logging back off after collecting the verbose .log). Put the .log file inside a .zip file to upload it to Github.
