### ISSUE TITLE
Just did a ship health check with compartment module checks, and most of variables result not set

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#2582]
## What's Wrong (please be as specific as possible)
Just did a ship health check with compartment module checks, and most of variables result not set. I think you guys should take a look. Not important but worth mentioning

### Expected
[Describe what you expected to happen]
Give values for most of module health etc..

### Observed
[Describe what actually happened. Feel free to add screenshots, link to videos, etc to help explain what happened]
Result Not set

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: latest
  * VoiceAttack Version: [if applicable] latest

## My Investigation
Tried to repeat wit same result

### Investigation Notes
[Any investigation you have done, tests using default scripts and personalities, regression tests against earlier versions, etc]

### EDDI Logs
[EDDI latest.txt](https://github.com/EDCD/EDDI/files/12650232/EDDI.latest.txt)

**Comment by Tkael** [comment]
Hi @FireSammy. I'm afraid that's the context of when and where you're making the request isn't sufficiently clear from the log you shared (I'd need a verbose log to see the context more clearly). 

I'm not sure which command you were looking at in VA (probably `((EDDI ship compartment variables))`)? Please confirm? A screenshot or two of the VA output so that I can see exactly what was not set would be helpful.

Module health specifically is set either from a `Loadout` event or from the Frontier API. It looks like you probably had both during your play session so the values should have been pretty well filled in. Please respond back with more detail so that I can investigate further.

o7

**Comment by Tkael** [comment]
Closing due to insufficient contextual information to investigate / replicate the issue.
