### ISSUE TITLE
Multiple variables bugged

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#2592]
6:14:09.561 Decimal token could not be converted : {DECINV:Ship life support health}
6:14:08.961 Decimal token could not be converted : {DEC:Ship large hardpoint 8 module health}
6:14:08.897 Decimal token could not be converted : {DEC:Ship large hardpoint 7 module health}
6:14:08.833 Decimal token could not be converted : {DEC:Ship large hardpoint 6 module health}
6:14:08.770 Decimal token could not be converted : {DEC:Ship large hardpoint 5 module health}
6:14:08.705 Decimal token could not be converted : {DEC:Ship large hardpoint 4 module health}
6:14:08.641 Decimal token could not be converted : {DEC:Ship large hardpoint 3 module health}
6:14:08.446 Decimal token could not be converted : {DEC:Ship medium hardpoint 8 module health}
6:14:08.377 Decimal token could not be converted : {DEC:Ship medium hardpoint 7 module health}
6:14:08.308 Decimal token could not be converted : {DEC:Ship medium hardpoint 6 module health}
6:14:08.243 Decimal token could not be converted : {DEC:Ship medium hardpoint 5 module health}
6:14:07.915 Decimal token could not be converted : {DEC:Ship small hardpoint 8 module health}
6:14:07.850 Decimal token could not be converted : {DEC:Ship small hardpoint 7 module health}
6:14:07.787 Decimal token could not be converted : {DEC:Ship small hardpoint 6 module health}
6:14:07.723 Decimal token could not be converted : {DECINV:Ship small hardpoint 5 module health}
6:14:07.659 Decimal token could not be converted : {DECINV:Ship small hardpoint 4 module health}
6:14:07.593 Decimal token could not be converted : {DECINV:Ship small hardpoint 3 module health}
6:14:07.527 Decimal token could not be converted : {DECINV:Ship small hardpoint 2 module health}
6:14:07.458 Decimal token could not be converted : {DECINV:Ship small hardpoint 1 module health}
6:14:07.392 Decimal token could not be converted : {DECINV:Ship compartment 11 module health}

**Comment by Tkael** [comment]
Hi FireSammy. I need more information to diagnose this issue so I'm going to close this and ask you to resubmit using the "Bug Report" template that Github provides when you create a New Issue. If you're able to provide a verbose log for this issue then that would be extremely helpful as well. 

If I have to guess on the conditions where this is occurring then it becomes much harder to arrive at the correct diagnosis for the problem.

As is, I don't know what version of VoiceAttack you are using, what version of EDDI you are using, how EDDI is configured, if this is a longstanding issue or a recent change in the behavior of the software, if your Frontier API connection is behaving correctly, etc.

The simplest explanation is that there was a problem accessing the Frontier API (since that is the sole mechanism for updating module health values) which left module health values (and perhaps other values?) null. VoiceAttack then generated an error because you asked it to convert a null value to a decimal. I can't confirm this or address any underlying issue with the Frontier API connection based on the limited information provided.
