### ISSUE TITLE
I want to be able to refer to gravity in variables.

### ISSUE THREAD

**Issue by Menon-F** [EDCD/EDDI#2620]
The 'Glide' script allows gravity to be spoken in EDDI, but it would be very helpful if this could be treated as a variable that can be used in the VA.

**Comment by Darkcyde13** [comment]
If it doesn't get added by the team, or can't be added, you can always set it as a State variable and then access that in VA.  So something like this...

Add this line somewhere after the `set reportBody to` line in the Glide event script:
`{SetState('eddi_body_gravity', reportBody.gravity)}`

Then in VA you can access that by using:
`{DEC: EDDI state eddi_body_gravity}`
It's a decimal because the .gravity property on reportBody is a decimal number.

This is usually how I send data to VA to be used.

**Comment by Tkael** [comment]
Please use the `SetState()` function to share the variable value with VoiceAttack.
https://github.com/EDCD/EDDI/wiki/VoiceAttack-Integration#setstate
https://github.com/EDCD/EDDI/wiki/Help#setstate
