### ISSUE TITLE
Galnet news published event not firing

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#2636]
## What's Wrong (please be as specific as possible)
Galnet news published event is not firing after new articles are published.
### Expected
Galnet news published event triggers when news published.

### Observed
Never get a "Galnet news published event" event. News is however read into the database and available to read, just never notified of news presence.

### Steps to reproduce
1. Wait for a galnet article to be published and notice no "Galnet news published event"

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.04
  * VoiceAttack Version: [if applicable] 1.14
* Localization [if applicable] EN
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"]
  * Voice: [Name and language]

## My Investigation
Looked at code . Believe all articles in Galnetmonitor,cs are not counted.
Logged `newsItems.Count` and it is always zero (0), whether there are new items or not.
 
Also, Primary feed URL is dead: https://elitedangerous-website-backend-production.elitedangerous.com/galnet.rss
Backup is still active: https://community.elitedangerous.com/en/galnet-rss

Tested against another feed at : **http://proxy.gonegeeky.com/edproxy/**
Suggest using that URL until #2415 is decided.

### Investigation Notes
[Any investigation you have done, tests using default scripts and personalities, regression tests against earlier versions, etc]

### EDDI Logs
[Any log files providing additional details about what happened. These are located at %APPDATA%/EDDI and have the extension ".log"]

No errors in log.

### Player journals
[These are not required if EDDI Logs are verbose but may be helpful otherwise. They are located at [your Saved Games folder]/Frontier Developments/Elite Dangerous/. Please only provide excerpts or attach files from the play session where the issue occurred.]

**Comment by Tkael** [comment]
Hi there, i just tested the latest build (where the Galnet Monitor is almost entirely unchanged from 4.0.4) and the `Galnet news published` event did correctly fire for the Galnet article which was published today. 

If the article was successfully saved to the database as you described then that indicates to me that the Galnet Monitor must have added the article to `newsItems`. Indeed my test today did show that `newsItems.Count` was greater than zero and the event did queue correctly and was spoken through the Speech Responder. 

If the event is being suppressed, perhaps it is being suppressed at the Speech Responder? 
- Please verify that the Speech Responder is enabled?
- Please verify that the `Galnet news published` event is enabled?
- If the `Galnet news published` event is enabled, is it set to the default script?
- Since you are using VoiceAttack, do you toggle the speech responder's state through your VoiceAttack profile (turning it on and off in response to various events)?

**Comment by rodan123** [comment]
OK.

Galnet monitor in EDDI is, and was, enabled. Nothing has changed on my end, except the EDDI version. 

I thought it was strange that the articles posted to the database, but not notifying.
I use the voice attack notification.  ((EDDI Galnet news published))
I don't use the EDDI script, so it is disabled.

On the event, all it does is set a variable to TRUE that's checked if I ask if there is news. I also used to see the event in VA's log, if it did fire and I have been looking but haven't seen it for the last few news articles that were published.

No worries, it looks like it might be only happening to my system, I'll look into it on this side.
