### ISSUE TITLE
EDDI is running in administrator mode without me telling it to

### ISSUE THREAD

**Issue by DawnTreader** [EDCD/EDDI#2650]
I don't know what caused this cause I have just done a brand new install of my computer and didn't do anything other than run the installer. Every time I try to Authenticate with Frontier it fails because EDDI, without me configuring anything, is apparently running in Admin mode.

**Comment by Tkael** [comment]
That is very odd. EDDI is not configured to always run in admin mode. When you run EDDI, are you being prompted to run in admin mode? What version of Windows are you using?

**Comment by DawnTreader** [comment]
There is no popup asking for admin mode. Windows 11 pro 23H2, build 22631.4169. And like I said, it is literally installed on 2024-09-13 around 7pm. I am still putting all my stuff back in place. I am an administrator user on the computer, would that have anything to do with it?

**Comment by Tkael** [comment]
Being an administrator shouldn't trigger that. Your Windows version isn't unusual either.

Since you're trying to authenticate with the Frontier API I imagine that you are not running EDDI as a VoiceAttack plugin / inheriting admin privileges from VoiceAttack.
You've checked the properties on the .exe file and any shortcut files to make sure they aren't providing instructions to run as an administrator?

You can also independently check whether EDDI really is running in administrator mode by following the instructions [here](https://superuser.com/questions/1213101/check-if-an-app-is-running-as-admin). Let me know what you see?

**Comment by DawnTreader** [comment]
Hello

Dang. 
![image](https://github.com/user-attachments/assets/4f0fd7e3-a85c-4f55-b300-1b8e74586f14)

I am elevated. and so no matter how I run EDDI it will run elevated.

However. I just managed to get it to work. EDDI told me that it was running in Admin mode but I was still able to get it to connect to the API. Additionally, I ran EDDI outside of VA to do so, then closed EDDI and opened VA and then configured EDDI and it was still connected. This time though it didn't complain about being elevated.
