### ISSUE TITLE
Companion API: Incorporate updates for E:D2.4

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#27]
https://forums.frontier.co.uk/showthread.php/373036-Changes-to-Companion-API-2-4-Open-Beta?p=5859432&viewfull=1#post5859432
- Some modifications for modules are now displayed in /profile, some modifications are not yet included (ship.modules entries have some new fields for engineers' mods.)
- Market & Starsystem controlling Factions & Superpowers displayed in /profile are now correct
- Added current ship's Fighters and / or SRVs to /profile
- Shield damage resistances should now be included on shield generators and boosters
- Display values should now be correct for modifiers where lower values are improvements

**Comment by richardbuckle** [comment]
What is the status on this? Do we need to break it apart into separate tasks?

**Comment by Hoodathunk** [comment]
I've not yet began the work in earnest. Partly because I'm waiting to see what shakes loose when 2.4 goes live. FDEV is infamous for changing data definitions during betas.

There's several new features that are being implemented in the 2.4 cAPI and I was planning on implementing in phases.

In rough order of lowest hanging fruit:
1. Ship name and idents now in profile shipyard data. Populate/update in ship objects
2. Ship Fighter & SRV bay presence and contents. Add to ship object.
3. Module engineer modification details added for current ship. Add new data to ship object and coordinate with EDCD Coriolis folks to follow their updated API for exporting ship configurations... this is obviously the most complex and challenging part.

If breaking down into smaller tasks would add value in tracking, then obviously I'm for it.

**Comment by richardbuckle** [comment]
Sounds sensible to me. Thanks for the update!

**Comment by richardbuckle** [comment]
Just a ping to see if we still need this ticket.

**Comment by Tkael** [comment]
action items are still present, but it may be easier if Hoodathunk could generate issues for each of the items that still need doing.

**Comment by richardbuckle** [comment]
Is there anything left to do here?

**Comment by Tkael** [comment]
1 & 3 are done (Coriolis just needed the raw, which we will now be providing correctly). I'm uncertain about 2.

**Comment by Hoodathunk** [comment]
Working on #2 next.
