### ISSUE TITLE
Request: Easy way to switch between Elite Dangerous accounts

### ISSUE THREAD

**Issue by The1AndMany** [EDCD/EDDI#310]
Some people have multiple accounts on Elite Dangerous, for various reasons ranging from "one account for exploration in the deep black, one for trading/combat in the bubble" to "starting from scratch without having to wipe a save". I'm considering getting a secondary account myself, but one of my hesitations is that I depend heavily on EDDI and a custom VoiceAttack profile. Currently, if I wanted to use EDDI with two separate accounts, it seems I would have to log out of the Frontier API then log back into the API with the other account and re-authorize the connection with a code from my email every time I switch between the two. This could be streamlined somewhat.

Potentially, I could check EDDI's settings (or just use a VoiceAttack command) to check which account EDDI is currently using and press a button (or use a different VoiceAttack command) to switch to a given API token without needing to check my email to re-authorize the connection. Better yet, if I specify in the settings which API token to use if it detects a certain player name in the journal, it could do this automatically behind the scenes.

I realize this may be a bit far-fetched and that my example may be flawed due to a less-than-comprehensive understanding of how EDDI interacts with the API, but it'd be a great quality-of-life improvement for anyone who uses EDDI and has multiple Elite Dangerous accounts.

Alternatively, Frontier could just figure out how to have multiple save files per account and tie that into the API, which would probably make this a lot easier. But I doubt that'll happen.

**Comment by Tkael** [comment]
There's more tied to the account than just your token. We'd need to segregate almost all of your config files including materials, cargo, ships, etc. by account as well (making this task more of a complex undertaking - EDDI wasn't really designed for this use case).

Furthermore, since the player journal does not write your commander name into the header, we cannot automatically segregate journal files by commander name or perform any automatic matching between the journal files and the information that we receive from the API. Consequently, if you were to forget to manually switch over then you'd write data to the wrong config files, corrupt those files, and end up with errors everywhere. 

Since the config files are unique to your windows account, some commanders with multiple accounts have set up secondary Windows user accounts to keep their configuration data from becoming mixed. For the short term at least, this is the best solution to using multiple Frontier API accounts with EDDI.

**Comment by The1AndMany** [comment]
Yeah, I figured it was much more complex than I could tell. I'm pretty sure I saw a "Commander" variable in the "Load Game" event, though. It doesn't always come first, but a slight delay in processing the other events that happen on load might be able to compensate. But if it has to be in the header, that's another story.

Thanks for the suggestion about alternate Windows user accounts, though. If each dummy Windows user account is logged into a different ED account, and assuming I understand correctly, I should be able to play ED with EDDI and VoiceAttack without having to keep switching API logins. That makes things much simpler than I thought it was. I'll keep that in mind.

But yeah, again, I didn't understand just how intricate things were. I knew getting this feature was unlikely, but I figured I'd at least ask. Thanks for the quick response!

**Comment by Tkael** [comment]
I think the bigger problem might be the lack of a constant id between both the journal and API. The API writes an id but there is no matching id given in the journal. If we tie all of your data to your commander name (which can change) then any change to your commander name would invalidate your prior data.

**Comment by The1AndMany** [comment]
Interesting. I have zero experience with coding with the Frontier API or even coding in C#, so I probably won't be able to help at all, but at least I know now.
