### ISSUE TITLE
EDDI crashes immediately on startup 

### ISSUE THREAD

**Issue by KingBuzzo1505** [EDCD/EDDI#328]
## EDDI version in which issue found
2.4.5 and also 2.4.6-b2

## Steps to reproduce

1. Open EDDI
2. 

## Expected
I expect EDDI to stay and log me in to the Frontier API

## Observed
EDDI crashes and also it says in EDDI that the frontier API is non-operational. This has happened since 4th January 2018
[eddi.log](https://github.com/EDCD/EDDI/files/1607933/eddi.log)

## Investigation
I deleted the credentials.json file from APPDATA folder but it still remains the same

**Comment by Tkael** [comment]
You appear to have a corrupted configuration file, but because of the asynchronous nature of the program it's hard to say which. Please 
1. Navigate to %APPDATA%/EDDI
2. Cut all of the files and paste them to another location
3. Attempt to start EDDI. EDDI should open with the default configuration.
4. Exit EDDI.
5. Cut and paste one of your configuration files into %APPDATA%/EDDI (overwrite as required)
6. Repeat steps 3 - 5 until EDDI fails to start. Remove the offending file(s) and reconfigure as necessary.

**Comment by KingBuzzo1505** [comment]
Excellent that worked, seems it was EDSM.json that was the culprit. Cheers for the help

**Comment by Tkael** [comment]
Glad to hear you were able to find the culprit. o7 cmdr!

**Comment by bsimpson82** [comment]
Thanks for this!
