### ISSUE TITLE
VA + EDDI : Disabling Sound Device

### ISSUE THREAD

**Issue by Atomskza** [EDCD/EDDI#348]
## EDDI version in which issue found
[2.4.5]

## Steps to reproduce

1. [give the fullest and most reproducible steps you can]

1.  Get a Speech Response from EDDI in game. 'Incoming Message From, Message Reads, Incoming 
     Message From - Pirate Wesley Snipes, Message Reads - What do you have for me today?. 
2. During or just after the Speech Response my Audio Drivers get killed. Speaker icon on taskbar with a 
    red cross through it. 
3. Waiting about 3 minutes for Windows to restart the service before audio works.
4. Have to close Voice Attack and Reopen.
5. Works fine until next Speech Reponse 'Message Receive' from EDDI.

**Audio Specs :**

Drivers : Realtec HD Audio Driver
Headset : Logitec Wireless Headset 933

Changed settings : 

TTS to Microsoft David
Logitec Wireless HS Mic settings changed to 1channel 16 bit 48000Hz DVD Quality

2. [the more reproducible, the better our chances of fixing it]

## Expected
Sound device to not get disabled.

## Observed
Sound Device gets disabled.

## Investigation
1. Disabled Plugin Support in VA (This fixes the problem)
2. Disabled Devices like USB Devices, Joystick and webcam. (No Fix)
3. Changed from default device to specific device. (No Fix)
4. Disabled EDDI Speech Response plugin (Fixes problem)
 a. Can't disabled the speech reponse 'Message Received' within EDDI speech Response Control Panel.
     (as per issue #325).
b. Changed to TTS Voice plugin, more stable! (Changed it when I was setting it up to Microsoft David)
c. Still need to test voice quality settings, I did change it to 48000hz DVD Quality on my default device(Will update soonest).

##Footnote
Hoping someone might have some insight on what else I can test to resolve the issue.

**Comment by Tkael** [comment]
Please provide a screenshot of your VoiceAttack '((EDDI message received))' command details? Are there any VoiceAttack actions present?

Please also provide a screenshot of VoiceAttack's log from just before and just after this occurs.

It should be possible to disable the 'Message received' script in EDDI's speech responder tab. Have you tried upsetting to the beta version, where you can more easily see whether it is possible to directly disable the script? (Note that the default personality is read only, you'll need to click the 'Copy personality' button and create writeable copy before you can disable this script)

If you click the 'Edit script' button and delete the contents of the 'Message received' script in EDDI's Speech responder tab, does the issue persist?

If you use speakers rather than a headset, does the issue persist?

As far as I'm aware, the behavior you're describing shouldn't be possible... The more data you can provide the better.

**Comment by Atomskza** [comment]
Didn't have time yet to test everything and should be able to give you an update a bit later today.

I did do some driver updates yesterday and so far it only happened once, that said I am running trade routes at the moment, so not getting scanned a lot which means less messages from pirates/feds. Will go do some bounty hunting to test.

Also set my mic back to 44.1kHz.

**Comment by Tkael** [comment]
Was this issue resolved?

**Comment by Atomskza** [comment]
Its seems like it is fixed now.

* Only changed to default TTS Voice
* Changed Audio Quality to 44.1kHz
* Updated both Realtek and Logitech drivers for sound devices.

Will be sure to let you know if this pops up again.

**Comment by Tkael** [comment]
Glad you were able to work it out. :-)
