### ISSUE TITLE
Functionality request

### ISSUE THREAD

**Issue by cmdrbarneyfive** [EDCD/EDDI#349]
Is it currently possible for me (with appropriate knowledge) or would it possible for you to add more variables to the current information available? I'm very new to EDDI so if I've overlooked something in the docs/website that would have answered this, excuse me.

I'm thinking specifically...

faction variable - the info you get when accessing the systems panel then paging to the "System Status" information
faction name
faction allegiance (fed, empire, alliance, independent)
cmdr influence level
cmdr influence trend (is influence going up/down/neutral)
cmdr status (wanted... etc.)
faction state (bust, boom, war, civil war... etc.)

panel variable - information on the four information panels in the cockpit
panel number (0, 1, 2, 3, 4)
panel name (navigation, communications, role switch, systems)
panel active (0=no active panel, 1=navigation, 2=communications, 3=role switch, 4=systems)
panel tabs collection
  panel tab number
  panel tab name
  panel tab active
  etc...
etc...
  

current locked target variable - information about your ship's current relative position to any locked target
name of target (planet name, NPC name, etc...)
distance in Ls/Mm/Km
distance in time

**Comment by Tkael** [comment]
Third party apps receive data in discrete packets rather than a continuous stream. See http://hosting.zaonce.net/community/journal/v13/Journal_Manual_v13.pdf to get a sense of the information that is available. Much of the information that you are requesting, especially fine position and targeting information, is not available.

- [ ] faction variable - the info you get when accessing the systems panel then paging to the "System Status" information **We could expand EDDI in this area and get an array of faction names, influence levels, and states. Honestly though, there are already tools which handle this data much better and EDDI's focus isn't on tracking BGS data.**
- [x] faction name **Already available via the 'Jumped' event variables**
faction allegiance (fed, empire, alliance, independent)
- [x] cmdr influence level **Not available**
- [x] cmdr influence trend (is influence going up/down/neutral) **Not available**
- [x] cmdr status (wanted... etc.) **Not directly available. It might be possible to achieve this by tracking crimes and bounties paid, but at present it couldn't by synced to your commander details so it might not capture every change. Likely not worth the effort required right now, especially considering the upcoming changes to the crime and punishment system.**
- [x] faction state (bust, boom, war, civil war... etc.) **Already available via the 'Jumped' event variables and the EDDP monitor**

- [x] panel variable - information on the four information panels in the cockpit  **Not available**
- [x] panel number (0, 1, 2, 3, 4)  **Not available**
- [x] panel name (navigation, communications, role switch, systems)  **Not available**
- [x] panel active (0=no active panel, 1=navigation, 2=communications, 3=role switch, 4=systems)  **Not available**
- [x] panel tabs collection  **Not available**
- [x] panel tab number  **Not available**
- [x] panel tab name  **Not available**
- [x] panel tab active  **Not available**
- [x] etc...  **Not available**
- [x] etc...  **Not available**

- [x] current locked target variable - information about your ship's current relative position to any locked target **Not available**
- [x] name of target (planet name, NPC name, etc...) **Not available**
- [x] distance in Ls/Mm/Km **Not available**
- [x] distance in time **Not available**
