### ISSUE TITLE
FSD Status

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#414]
## FSD status 3.0.0-b2
3.0.0-b2 Voice Attack and standalone]
Minor impact. fsd status returns unexpected values.

Documentation is incomplete.
Additional fsd status values; "masslock cleared" , "charging complete" , and "cooldown complete" are coded and can be returned.

**Comment by Tkael** [comment]
The distinction is that the values you identified will only survive for one tick of the status monitor and were intended to be used in the context of the `Ship FSD` event while the values that are documented are persistent across multiple ticks of the status monitor. Consequently, these "instant" values are documented, but only in the context of the `Ship fsd` event: `fsd_status` `The status of your ship's fsd ('cooldown', 'cooldown complete', 'charging', 'charging complete', 'masslock', or 'masslock cleared')`.

I didn't add them to the general variable description because I didn't see utility in noting them outside of the applicable event.  What utility do you see in adding them there?

**Comment by rodan123** [comment]
I have seen them returned in Voice Attack when calling for the variable. It confused my VA script, because I only expected the documented values to be returned. IMO all the 'complete' and 'cleared' return values should simply return 'ready'

**Comment by Tkael** [comment]
PR #419 created to address this concern. Closing this issue pending acceptance of the PR.
