### ISSUE TITLE
Setting an update as mandatory crashes EDDI

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#493]
If an update is marked as mandatory, EDDI crashes because it exits before instantiaing `EDDI.Instance.Cmdr` and the MainWindow then tries to set the gender of that null object.

Before blindly fixing this I want to get a better understanding of what it means to mark an update as mandatory and why the code is doing what it does.

**Comment by Tkael** [comment]
Looks like setting an upgrade to mandatory prevents EDDI from initializing an instance (when `running` is set to false by the mandatory upgrade, `instance = new EDDI();` returns null at EDDI.cs line 69. and since the instance is not initialized subsequent attempts to set instance specific variables result in exceptions & crashes).

Deleting EDDI.cs line 136 (which tells EDDI to return a null value for the instance) should resolve the issue. Unfortunately, that simple fix also makes upgrades a lot less mandatory. So we need to ask what we want a mandatory upgrade to mean?

If any upgrade is mandatory then we don't want to prevent EDDI from running, at least in a limited, read-only fashion, but we do want to prevent it from sending bad data out. So I propose we 
1. disable all responders and 
2. disable the StarMap service 
by making them conditional on `running` being set to `true`.

Thoughts?

**Comment by richardbuckle** [comment]
Sounds reasonable. Let me take a little time to reflect. 
Maybe also disable export to Coriolis / EDShipyard?
I'm debating whether to halt the journal parser as well.

**Comment by Tkael** [comment]
Why disable export and the journal parser? The export does send data out, but it can't negatively impact other users. And the journal monitor doesn't send data out on its own at all. We don't need to cripple old installations if we don't have a good reason to do so.

**Comment by Tkael** [comment]
Also... I'd rather keep any code dealing with this localized... not spread out.

**Comment by richardbuckle** [comment]
Good points.

I’ve still got that darn “something is missing” feeling in the back of my mind that I can’t quite pin down. Maybe a good night’s sleep will help.

**Comment by richardbuckle** [comment]
Just thinking aloud. The only reason you’d mark an update as mandatory is if it fixed a bug that was harmful in some way, such as submitting incorrect data. But it could be something that’s only dangerous to the local machine such as a catastrophic bug in a file parser that nukes the file system in certain rare circumstances. I know that is far-fetched but humour me here. 

I’m thinking it should stay in some sort of “safe mode” until the update is complete. It’s going to update itself immediately anyway, so we’re not really crippling it for any great length of time.

I’m open to persuasion on this one though. Still haven’t really made my mind up.

**Comment by Tkael** [comment]
A 'safe mode' is exactly what I was proposing... now we're just discussing the extent of it. The extreme version would probably disable all monitors, all responders, and all methods that write to config files.

**Comment by richardbuckle** [comment]
I think we can close this now.
