### ISSUE TITLE
EDDI Core: Add support for localization / translations to non-English languages

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#50]
Suggestion from Syrrianyl:
For the MissionAcceptedEvent, EDDI take actualy the comodity with
Commodity commodity = CommodityDefinitions.FromName(getString(data, "Commodity"))
, is it not better to use the Commodity_Localised with
string commodity = getString(data, "Commodity_Localised");
and now we have also a LocalisedName for the name of the event, so is it better to replace
'string name = getString(data, "Name");'
by
'string name = getString(data, "LocalisedName ");'
or it is better to add a new like this
string localisedname = getString(data, "LocalisedName"); and rework all the MissionAcceptedEvent by adding a value like:
MissionAcceptedEvent(timestamp, missionid, name, faction, destinationsystem, destinationstation, commodity, amount, passengertype, passengerswanted, target, targettype, targetfaction, false, expiry, influence, reputation, localisedname)

A similar approach is likely possible with other events.

**Comment by Tkael** [comment]
I'd rather add a new variable, like 'localisedname', to applicable events containing the localized name. Replacing the existing names could break things, both in EDDI and also in scripts that people have already worked hard to make. Please send pull requests with any localized variables that you'd like to add so that we can review them?

**Comment by Syrrianyl** [comment]
For localisation, To add new variable is a good idea, but not for change what it exist already.
My idea to have a full french EDDI look bad because many scripts already exist and changes looks too big for users.
When I look, french users use the work of the german-one (vith scritp "Translate xxx" link [here](http://snafets.de/elite/eddi_scripts/index.php?show=10#script_1227)
for exemple with elements in Body report:
`{set translate to goodmaterials[0].name} {F("Translate Element")}`.

So, for priority, low, or very low. To look after the 2.4 evolution, when all others work well to have a extern file of localisation that not need to rebuilt the source code each time a new word have a translation.

Actually I translate the user interface, with materials listed in "Material monitor" and some parts in the translation.cs (actually more look too much)

**Comment by Tkael** [comment]
Closing, implemented. :-)
