### ISSUE TITLE
Un-localized reference documents on EDDI's update server broken

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#595]
## EDDI version in which issue found
3.0.1-b2 standalone and develop branch

## Steps to reproduce

Test the "Blueprint make report" script in the speech responder tab.

## Expected
A blueprint report

## Observed
Null dereference in `public MaterialAmount(string edname, int amount, int? minimum, int? desired, int? maximum)`.

## Investigation
Same old JSON parsing issue as before.

**Comment by Tkael** [comment]
Same is true for all un-localized reference documents on EDDI's update server.

**Comment by richardbuckle** [comment]
Very true. Need to consider best approach. Add “edname” keys to server data? 
I need to reflect on this, especially in the light of the current bonus weekend.

**Comment by Tkael** [comment]
- [ ] Update BlueprintRequirements.json (or link to a more continuously updated source).
- [ ] Replace MaterialUses.json with a function which compile lists of applicable blueprints for a given material (so that we don't need to continue to maintain this list).
- [ ] Replace MaterialLocations.json with a translatable resx file.
