### ISSUE TITLE
Galnet (for Beyond) - proposal 

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#599]
The category assignments for Galnet news haven't been working since fdev revamped the galnet feed.
I didn't see the Galnet code listed as being scheduled for an update, so... 

I have revised the code to sort the galnet news into 4 categories;
1) Article
2) Starport Status Update
3) Week in Review 
4) Community Goal
Article being general galnet news, the other categories are self explanatory.

I have mocked up a PR branch; https://github.com/rodan123/EDDI/tree/feature/galnet30

The category assignment is all in _GalnetMonitor/GalnetMonitor.cs_ 

I also did a small optional change that adds a `ReplaceStrings (string)` function to _GalnetMonitor/GalnetFeedItemNormalizer.cs_ and it currently replaces the word **Thargoid** with **Thargoyd** to attempt a better pronunciation than the current Thar-go-id. I noted below that in a commented section how I am using more substitutions to get better pronunciations of dates in the news.

So far It has been working pretty well for me and I offer it here for consideration to merge with the codebase.

**Comment by Tkael** [comment]
@richardbuckle It looks like GalnetMonitor.cs may benefit from conversion to a resx format. Thoughts?

**Comment by rodan123** [comment]
While on the subject, way back I noticed there is no mechanism in EDDI to clean out old galnet articles,

Below is cottle script that I launch on every "Galnet news published event"
I have been using it for quite a while to keep the database tidy.

I have it set to keep only the latest 20 articles by setting the `max_articles` variable.

'{_ Clean out old articles from database> Keep only max_articles items.}

{set max_articles to 20}
{set articles to GalnetNewsArticles("All",true)}
{set tot_articles to len(articles)}
{if tot_articles >= max_articles:
  {while max_articles <= tot_articles):
    {GalnetNewsDelete(articles[tot_articles].id)}
    {set tot_articles to tot_articles-1}
   }
}'

**Comment by Tkael** [comment]
I'm not sure whether most people would want a way to clean out old galnet articles. There's something to be said for having a database that is locally searchable.

It's generally a bad idea for us to hardcode a deliberately misspelled word pronunciation into EDDI based on the pronunciation produced by a single voice (pronunciation can vary significantly from voice to voice and deliberate misspellings / text replacements make the articles as a whole less searchable).  Pronunciation issues need to be addressed when the speech is being generated rather than when the item is received and entered into the database. @richardbuckle has wanted to add a lexicon to EDDI to make custom pronunciations easier for individual commanders. #98 is where he's been collecting items with dubious pronunciations (including `thargoid`).

I've submitted a PR to help address the category issues you mentioned.

**Comment by rodan123** [comment]
Points taken. Thanks for looking at this.
