### ISSUE TITLE
Body & Star scanned in Voice attack get triggered when scanning Nav beacon

### ISSUE THREAD

**Issue by BeBumble** [EDCD/EDDI#638]
## EDDI version in which issue found
EDDI v.3.0.1-b4

## Steps to reproduce

1. When scanning nav beacon to get system info it triggers ((EDDI Body scanned)) & ((EDDI star scanned)) in Voice Attack
2. Just scan a nav beacon you havent got any plant or star data on

## Expected
((EDDI body scanned )) & ((EDDI Star scanned)) not to be triggered in Voice attack

## Observed
My star and body scanned scripts get triggered adding to my custom exploration scans

## Investigation
N/a

**Comment by rodan123** [comment]
It's been that way forever.
I believe it is expected behavior, since someone may want to collect all that data. 
I use the variable `event.numbodies` (VA `EDDI nav beacon scan numbodies`) and have the other reporting scripts do nothing if it is set. 
I am sure you know there is a separate _Nav beacon scan event_
Between that and the other fired scan events it makes the nav beacon scan much more customizable than just having it return the number of bodies in the system,

**Comment by Tkael** [comment]
This is something that is actually inherent to the the way the player journal works. We actively have to suppress these events during a nav beacon scan. I'm not sure why that suppression didn't work but I'll see if I can replicate what you are describing.

**Comment by Tkael** [comment]
Update: I've tested this at several systems that I was visiting for the first time and I wasn't able to replicate this. 
The most likely scenario for what you are describing would be if EDDI failed to handle the `NavBeaconScan` event correctly. 
Please search the journal for the applicable `NavBeaconScan` event and post it here?
Please also search EDDI.log for any exceptions that may be related to this event and post them here if applicable.

**Comment by BeBumble** [comment]
I'll see what i can do next time I'm on, first time i've done a report though here so bear with me

**Comment by Tkael** [comment]
Hi @BeBumble, any updates on this?

**Comment by BeBumble** [comment]
Sorry been away for abit will try and get a log of it in the next couple of days

boo yah ö7

**Comment by Tkael** [comment]
Closing due to inability to replicate this issue.
