### ISSUE TITLE
EDDI won't let me put in my home system

### ISSUE THREAD

**Issue by PrincessEggplant** [EDCD/EDDI#792]
EDDI v3.0.1

Steps to reproduce

Click on Commander details
Click in the home system text box
Input home system (LTT 7488)

Expected

EDDI accepts the home system. 

Observed

The text box goes red, and when I click off of it it clears the field.

Investigation

In my previous home system, EZ Aquarii, it worked fine. I can find LTT 7488 on EDDB and EDSM fairly easily. Also, I can input my home station, Rubin Vision, just fine. It's only the system that it clears.

**Comment by Tkael** [comment]
EDDI validates the system by checking whether the count of bodies (planets, moons, etc.) associated with that name is greater than zero. Since LTT 7488 has zero bodies and 5 stations, validation failed.
I'm submitting a change request to expand the validation rules to include bodies, stations, or population > 0.

**Comment by PrincessEggplant** [comment]
Thank you very much!

**Comment by richardbuckle** [comment]
Clearly from https://eddb.io/system/bodies/12805, which lists only bodies 6d and 7b, EDDB has incomplete data. But that's really neither here nor there, we need this fix.

**Comment by richardbuckle** [comment]
Fixed for 3.0.2-b1
