### ISSUE TITLE
crash when updating and no more offline Galnet reading

### ISSUE THREAD

**Issue by LesserHellspawn** [EDCD/EDDI#825]
## EDDI version in which issue found
3.0.3-rc1 standalone

## Steps to reproduce

Click the upgrade button when an update is available.
Enable Galnet offline reading.

## Expected

EDDI should upgrade.
EDDI should read missed Galnet articles on startup and keep reading new ones as they appear while I'm not in the game.

## Observed

EDDI crashes, then correctly updates after restarting it.
Galnet is only being read ingame.

## Investigation

Has been like that for at least the last 3 versions.

**Comment by Tkael** [comment]
Which? Or both? There seem to be two issues mixed here and not enough detail on either. 

I just ran an upgrade from version 3.0.2-b2 to version 3.0.3-rc1 without issues.
If EDDI fails to upgrade, generate and attach a log file so that we can review the log?

If EDDI fails to read Galnet articles on startup, verify that both the `Plugin enabled` and the `Read Galnet articles when logged out` buttons are checked?

**Comment by Tkael** [comment]
Closing as confusing with two mixed issues and with insufficient info to reproduce. Please attempt the steps detailed at https://github.com/EDCD/EDDI/blob/master/TROUBLESHOOTING.md#eddi-doesnt-start-or-crashes-on-startup and submit discrete issues for each item with the info requested if the issues persist. Thanks,
