### ISSUE TITLE
Request for VA variable: Station Advanced Maintenance?

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#856]
Just a humble wish, i've been waiting quite some time, few years lol. I would recon, since the ED maps do not provide this quite important station info (incredible as it is) was wondering have you guys check'd this thing out lately if it would be possible to dig it up? There are some fantastic new variables for VA which i've been updating the whole day, thx cheers!! :)

{BOOL:Last station has refuel}: true if this station has refuel capability
{BOOL:Last station has rearm}: true if this station has rearm capability
{BOOL:Last station has repair}: true if this station has repair capability
{BOOL:Last station has market}: true if this station has a commodities market
{BOOL:Last station has black market}: true if this station has a black market
{BOOL:Last station has outfitting}: true if this station has outfitting
{BOOL:Last station has shipyard}: true if this station has a shipyard

Would be great to have all station services (facilities -even) listed here, but i understand if/when not all are available from frontier as usual.

**Comment by Tkael** [comment]
In this case their are two issues 

1. Station services aren't included in EDDB daily dumps (which is the source we use to derive much of EDDI's station info). All we get are select true/false properties. Here's an example of the data from Jameson Memorial:
```
            "has_blackmarket": false,
            "has_market": true,
            "has_refuel": true,
            "has_repair": true,
            "has_rearm": true,
            "has_outfitting": true,
            "has_shipyard": true,
            "has_docking": true,
            "has_commodities": true,
```

2. Per the journal manual, StationServices can include: 
Dock, Autodock, BlackMarket, Commodities, Contacts, Exploration, Initiatives, Missions, Outfitting,CrewLounge, Rearm, Refuel, Repair, Shipyard, Tuning, Workshop, MissionsGenerated, Facilitator, Research, FlightController, StationOperations, OnDockMission, Powerplay, SearchAndRescue,
I'm not certain which of these, if any, would correspond to advanced maintenance. Do you have an example of a station with and without station services so that we can compare?

**Comment by Tkael** [comment]
After a bit more research, I've ruled out "tuning". https://www.reddit.com/r/EliteDangerous/comments/57fmio/beta_feedback_stream_2_qa_summary/?sort=confidence&utm_source=mweb_redirect&compact=true
`Q: I was wondering if you could take a moment to elaborate of the two seemingly new entries in the Facilities listing for Star ports in the System Map: Tuning & Auto-Dock`
`A: They're not new, but relics. Auto-docking just describes whether docking computer would work at a station, not really needed now. Tuning has turned into Outfitting and Engineer upgrades.`

**Comment by Tkael** [comment]
Closing as not currently possible. Sorry about that.
