### ISSUE TITLE
((EDDI ship fsd)) "charging complete" not reported until jump complete. [voiceattack]

### ISSUE THREAD

**Issue by antrys** [EDCD/EDDI#886]
## EDDI version in which issue found
3.1.0-b2
## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
Using this code in VA
-------
`Command Name: ((EDDI ship fsd))
Begin Text Compare : [EDDI ship fsd fsd_status] Equals 'charging complete'
    Say, 'Engaging.'
End Condition`
-------
## Expected
Report FSD Charge complete when the charge is complete

## Observed
Does not trigger until the entire jump is complete and you enter the destination system.
Or Until you fully enter SC from normal space.
Also Triggers on a canceled jump.

## Investigation
Most likely caused by the ED journal not actually reporting it until the jump is complete.
It's triggering at the same time as ((EDDI jumped))
Should this be removed? Or is it just poorly documented in the WIKI?

**Comment by Tkael** [comment]
Hmm... `charging complete` is currently written according to when Elite Dangerous writes that status. You're right to point out that the timing when it is officially written feels "off" relative to in-game events.

We may want to change this so that `charging complete` triggers when
1. `fsd status` is charging and
2. the ship is no longer in normal space
rather than waiting for the official `charging complete` signal from Elite Dangerous like we do now.

Likewise, we may want to consider creating a synthetic `fsd canceled` fsd status (since the journal doesn't give us something specific for this) that would be triggered when
1. fsd status is `charging complete` and
2. the ship is still in normal space.

**Comment by antrys** [comment]
I agree that sounds like a solution.
As long a Frontier doesn't fix it in the future!
That's one of those deals where you can have a lot of commands dependent off of one kludge and can be a pain to trace the problem down in the future.

**Comment by Tkael** [comment]
On further reflection, the `FSD engaged` event triggers when the countdown begins in your cockpit and is the best signal for determining that the fsd status should be changed to `charging complete`. Environment is temporarily unset while you transition to witchspace and consequently is a less reliable signal.
