### ISSUE TITLE
((EDDI Cargo Inventory)) triggered on every dropdown and jump completion and shipchange event.

### ISSUE THREAD

**Issue by antrys** [EDCD/EDDI#920]
## EDDI version in which issue found
3.1.0.rc1  voiceattack plugin. (with the ED 3.3 Beta )
## Steps to reproduce
Jump into system, drop from a hyperspace jump or drop from supercruise.

## Expected
Nothing (No report at this event)

## Observed
((EDDI cargo inventory)) event is triggered every time.
## Investigation
Every time I drop from cruise it causes my "Inventory report" to go off.
Also every time I change ships, or do anything where there is a change of "state" in the game.
It looks like they've changed the journal to report inventory on every dropdown event in more places.

I've had to disable my function in VA because it's gotten very annoying.
You should be able to call on it's variables if you want to, but not be forced to have it trigger on every jump.

**Comment by Tkael** [comment]
@antrys Please re-write your custom script to make use of the `inventory` object, triggered from the `Commander continued` event if you are interested in receiving a report when you first log into the game. Please don't script using the `Cargo inventory` event for the time being.

@Hoodathunk I think we'll need to look at suppressing extraneous `Cargo inventory` events, and may even need to hide the event from the UI since it's not being triggered in a manner that is suitable for scripting. See the `Status` event for an example of what I mean.

**Comment by Hoodathunk** [comment]
Few things going on here.
1. The reporting during FSD state changes is an FDEV bug that will be fixed in beta 3.
2. Chapter 4 cargo reporting is requiring a major re-write to the cargo monitor. I have mostly completed that but the community will not see it until our first offical Chapter 4 EDDI update.
3. @Tkael  has a point and I will likely remove the "Cargo" event from being triggered in Cottle & VA.

**Comment by Hoodathunk** [comment]
Fixed in 3.3 release.
