### ISSUE TITLE
shutup -script command does not seem to work

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#927]
## EDDI version in which issue found
Latest EDDI beta 3.1.0-rc1

## Expected
EDDI will continue talking as long as the text script lasts and also seems to hold VA commands/strings proceeding. I don't recall this happening before.

**Comment by rodan123** [comment]
I have the same issue with 3.1-RC1. While EDDI is speaking via a cottle script all VA functionality is suspended and VA commands are ignored, whether they be spoken or scripted. As above, this includes the VA command that sends "shut up" command to the cottle script, so it is impossible to stop the speech and all VA control is lost. Reverted to 3.1-B4 and the problem is gone.  

Also, 3.1-RC1 corrupts or changes the StarSystem SQL database requiring a re-sync from EDSM to repair.

**Comment by Tkael** [comment]
Thanks for the report. I was trying to limit simultaneous interactions with VoiceAttack to reduce some stuttering I'd noticed in the chapter 4 beta. I've backed off on that approach, rc2 should be better.
@rodan123 Yes, the sql database is changed by the rc1 update. When EDDI encounters old data, it logs it and then reaquires new data from the EDSM API. Re-syncing from EDSM isn't required but is encouraged since that will result in a cleaner log file.

**Comment by FireSammy** [comment]
Fixed = Working ok after latest update versions with both VA and EDDI in live ED (not playing beta version)
