### ISSUE TITLE
"Docking granted" sample / test event throws exception

### ISSUE THREAD

**Issue by hoksilato2** [EDCD/EDDI#940]
## EDDI version in which issue found
EDDI 3.1.0 under VoiceAttack

## Steps to reproduce

1. Open "Docking granted" script in EDDI
2. Use test script button

## Expected
Script works :)

## Observed
"Docking granted" are too much different in the new eddi.json. 

## Investigation
This script are broken in english too. variable {event.stationDefinition.basename} not work I think. I'm spanish user.

**Comment by hoksilato2** [comment]
Something wrong with this script?

```
{_ Context }
{SetState('eddi_context_last_subject', 'landing pad')}
{SetState('eddi_context_landing_pad_system', system.name)}
{SetState('eddi_context_landing_pad_station', event.station)}
{SetState('eddi_context_landing_pad_station_model', event.stationtype)}
{SetState('eddi_context_landing_pad_pad', event.landingpad)}

{if event.stationDefinition.basename = "Coriolis" || 
    event.stationDefinition.basename = "Orbis" || 
    event.stationDefinition.basename = "Bernal" || 
    event.stationDefinition.basename = "AsteroidBase":
    {Pause(8000)}
    {F("Landing pad report")}
}
```

There is my old code with spanish users:

```
{_ Context }
{SetState('eddi_context_last_subject', 'landing pad')}
{SetState('eddi_context_landing_pad_system', system.name)}
{SetState('eddi_context_landing_pad_station', event.station)}
{SetState('eddi_context_landing_pad_pad', event.landingpad)}

{set station to StationDetails(event.station)}
{if station.model = "Estación clase Coriolis" || station.model = "Estación clase Orbis" || station.model = "Estación clase Ocellus" || station.model = "Base en asteroide" || station.model = "Estación desconocida":
    {Pause(8000)}
    {F("Landing pad report")}
}
```

**Comment by Tkael** [comment]
The test script is old and out of date. EDDI is throwing an exception because it expects to see a `MarketId` value (which is now always present in the journal for these events). We'll update the test script to include a `MarketId`.

The `Docking granted` event script was updated in version 3.0.1-rc1 to use new data added to the journal. Using `StationDetails()` is no longer necessary, and hasn't been for some time. All of the information we need for landing pad reports is now given directly by the event. 

We recommend using `event.stationDefinition.basename` because that value is constant no matter what language you are using, while a translated string can change if someone revises the translation. But if you prefer the Spanish names, they are currently translated as follows:
- Base Asteroide
- Puerto Espacial Ocellus
- Puerto Espacial Coriolis
- Mega-nave
- Puerto Espacial Orbis
- Puesto avanzado
- Estación Planetaria
- Estación desconocida

**Comment by hoksilato2** [comment]
But if i use eddi in english and eddi.json the script doesn't work too. Whats wrong?

Thanks for your info.

**Comment by Tkael** [comment]
Correct. It'll work in game but the test script is currently obsolete.

**Comment by richardbuckle** [comment]
Fixed for the Chapter 4 release.
