### ISSUE TITLE
no frontier API connection for 48+ hours

### ISSUE THREAD

**Issue by JWyllieDev** [EDCD/EDDI#998]
2.4.5 VoiceAttack

## Steps to reproduce

1. try to sign in with frontier API

## Expected
login successful

## Observed
error message: "Unable to log in. This is usually as temporary issue with Frontier's service." etc etc etc

the issue i'm having is that this seems to be a long-running issue, easily 48 hours

**Comment by Tkael** [comment]
The Frontier API has changed its authentication protocol and we were not given the transition period that we were promised. This means that for the time being, the API is unavailable to EDDI. EDMC and EDDiscovery are in the same boat.

Also, development hasn't stopped. The old update server gave up the ghost at about version 2.4.5 but new releases are available from https://github.com/EDCD/EDDI/releases and you'll be notified of updates again once you upgrade to a supported version.

**Comment by syfy88man** [comment]
WOW and here I thought it was the Hutton Orbital Helper App that was having problems connecting and helping us in the game, Hutton Orbital Space Trucker group that I am part of has a little app and lately it keeps saying Frontier Server is down but their app seems to be still following and helping out with us in the game but now I see what happened. I decided to return to this app since it worked so well with my voice attack software and miss the extra info I would hear while listening to my HCS voice packs.
